<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tl</string>
	</array>
	<key>name</key>
	<string>TL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#sections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#combinator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#modifier</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>combinator</key>
		<dict>
			<key>begin</key>
			<string>((?:[a-z]\w*\.)?[a-z]\w*)(#[[:xdigit:]]{1,8})?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.tl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.tl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>=\s*(.*);</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&lt;==\s)(?:[a-z]\w*\.)?[A-Z]\w*</string>
							<key>name</key>
							<string>entity.name.type.tl</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>support.variable.tl</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#template_arg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.tl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.tl</string>
				</dict>
			</array>
		</dict>
		<key>field</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+(?:\s*)(?=:)</string>
					<key>name</key>
					<string>support.variable.tl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+\.\d+\?</string>
					<key>name</key>
					<string>string.unquoted.tl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#repeated</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#</string>
					<key>name</key>
					<string>constant.character.tl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\()[%]?(?:[a-z]\w*\.)?\w+</string>
					<key>name</key>
					<string>keyword.control.tl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>storage.type.tl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>constant.numeric.tl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[%]</string>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</array>
		</dict>
		<key>modifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[@]\b(?:read(?:write)?|write|any|kphp|internal)\b</string>
					<key>name</key>
					<string>constant.character.tl</string>
				</dict>
			</array>
		</dict>
		<key>repeated</key>
		<dict>
			<key>begin</key>
			<string>(?:(\w+)(?:\s*)\*(?:\s*))?(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\d+</string>
							<key>name</key>
							<string>constant.numeric.tl</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-zA-Z]+</string>
							<key>name</key>
							<string>constant.character.tl</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.repeated.end.tl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.repeated.end.tl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
			</array>
		</dict>
		<key>sections</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[-]{3}(?:type|function)s[-]{3}</string>
					<key>name</key>
					<string>string.unquoted.tl</string>
				</dict>
			</array>
		</dict>
		<key>template_arg</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.tl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.tl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\w+</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.variable.tl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>Type|#</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.tl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>:</string>
							<key>name</key>
							<string>punctuation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tl</string>
	<key>uuid</key>
	<string>BD867BBF-863A-48FB-BE0B-ADDD5EC91E36</string>
</dict>
</plist>
