// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package genphp

import (
	"fmt"

	"github.com/VKCOM/tl/internal/pure"
	"github.com/VKCOM/tl/internal/puregen"
	"github.com/VKCOM/tl/internal/tlast"
	"github.com/VKCOM/tl/internal/utils"
)

// For debugging
var DEBUG = true

func Debugf(format string, args ...interface{}) {
	if DEBUG {
		fmt.Printf(format, args...)
	}
}

type Namespace struct {
	types []*TypeRWWrapper
	decGo Deconflicter
}

type genphp struct {
	kernel *pure.Kernel

	// options
	options *puregen.Options // pointer so code modifying options in GenerateCode refers to the same structure

	// parsed TL
	allAnnotations []string // position is bit

	// generation
	builtinTypes       map[string]*TypeRWWrapper
	generatedTypes     map[string]*TypeRWWrapper
	generatedTypesList []*TypeRWWrapper // we need more deterministic order than sort predicate can establish

	globalDec  Deconflicter
	Namespaces map[string]*Namespace // Handlers Code is inside

	Output        puregen.OutDir
	copyrightText string
}

func canonicalGoName(name tlast.Name, insideNamespace string) string {
	if name.Namespace == insideNamespace {
		return utils.CNameToCamelName(name.Name)
	}
	return utils.CNameToCamelName(name.Namespace) + utils.CNameToCamelName(name.Name)
}

func (gen *genphp) getNamespace(n string) *Namespace {
	na, ok := gen.Namespaces[n]
	if !ok {
		na = &Namespace{}
		gen.Namespaces[n] = na
		// TODO - ALL golang-specific names
		na.decGo.deconflictName("Handler")
		na.decGo.deconflictName("Handle")
		na.decGo.deconflictName("Client")
		// TODO - if we want lowercase C++ identifiers, we need to add ~100 reserved keywords here
		// na.decCpp.deconflictName("double")
		// na.decCpp.deconflictName("int")
		// etc...
	}
	return na
}

func prepareNameFilter(name string, filter string) pure.Whitelist {
	return pure.NewWhiteList(name, filter)
}

func inNameFilter(name tlast.Name, filter pure.Whitelist) bool {
	return filter.HasName(name)
}

// WriteToDir Most common action with generated code, so clients do not repeat it
func (gen *genphp) WriteToDir(outdir string) error {
	return gen.Output.Write(gen.options, outdir)
}

func (gen *genphp) addCodeFile(filepathName string, code string) error {
	return gen.Output.AddCodeFile(filepathName, code)
}

func Generate(kernel *pure.Kernel, options *puregen.Options) error {
	options.Kernel.InstantiateConstants = false
	options.Kernel.InstantiateExclamationWrappers = true
	options.Kernel.NatArgsDelimiter = "_"
	options.Kernel.NotSimplifyNatArgs = true

	if !options.PHP.UseBuiltinDataProviders {
		panic("usage of \"UseBuiltinDataProviders\" is currently mandatory")
	}

	if err := kernel.Compile(); err != nil {
		return err
	}

	gen, err := generateCode(kernel, options)
	if gen == nil {
		return err
	}

	if err = gen.WriteToDir(options.Outdir); err != nil {
		return err // Context is already in err
	}
	return err
}

func generateCode(kernel *pure.Kernel, options *puregen.Options) (*genphp, error) {
	if options.Kernel.Verbose || DEBUG {
		if DEBUG {
			Debugf(">>> [WARNING] DEBUG = true <<<\n")
		}
		DEBUG = true
		Debugf(">>> [WARNING] ENABLED DEBUG MODE <<<\n")
	}

	gen := &genphp{
		kernel: kernel,

		options:    options,
		Namespaces: map[string]*Namespace{},
		// Files:                 map[string][]*TypeRWWrapper{},
		builtinTypes:   map[string]*TypeRWWrapper{},
		generatedTypes: map[string]*TypeRWWrapper{},
	}

	if err := gen.compile(); err != nil {
		return nil, err
	}

	switch options.Language {
	case "php":
		{
			// TODO ADD FEATURE TO CHANGE IT
			gen.copyrightText = `/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

`
		}
		if err := gen.generateCodePHP(); err != nil {
			return nil, err
		}
	default:
		return nil, fmt.Errorf("unsupported language: %s", options.Language)
	}

	return gen, nil
}
