package speed

// Code based on the one generated by https://github.com/hrissan/protocute

import (
	"fmt"
	"math"

	"google.golang.org/protobuf/encoding/protowire"
)

func protobufError(n int) error {
	return protowire.ParseError(n)
}

/*
	func protoReadString(buf []byte, result *[]byte) ([]byte, error) {
		data, n := protowire.ConsumeBytes(buf)
		if n < 0 {
			return buf, protobufError(n)
		}
		*result = append((*result)[:0], data...)
		return buf[n:], nil
	}

	func protoReadFloat64(buf []byte, result *float64) ([]byte, error) {
		data, n := protowire.ConsumeFixed64(buf)
		if n < 0 {
			return buf, protobufError(n)
		}
		*result = math.Float64frombits(data)
		return buf[n:], nil
	}

	func protoReadInt64(buf []byte, result *int64) ([]byte, error) {
		data, n := protowire.ConsumeVarint(buf)
		if n < 0 {
			return buf, protobufError(n)
		}
		*result = int64(data)
		return buf[n:], nil
	}
*/
func protoReadUint32(buf []byte) (uint32, int) {
	data, n := protowire.ConsumeVarint(buf)
	if n < 0 {
		return 0, n
	}
	if data > math.MaxUint32 {
		return 0, -3
	}
	return uint32(data), n
}

/*
	func protoReadPackedFixedFloat64(buf []byte, result *[]float64) ([]byte, error) {
		data, n := protowire.ConsumeBytes(buf)
		if n < 0 {
			return buf, protobufError(n)
		}
		if len(data)%8 != 0 {
			return buf, fmt.Errorf("packed double is not multiple of 8")
		}
		for i := 0; i < len(data); i += 8 {
			*result = append(*result, math.Float64frombits(binary.LittleEndian.Uint64(data[i:])))
		}
		return buf[n:], nil
	}

	func protoReadPackedVarInt64(buf []byte, result *[]int64) ([]byte, error) {
		data, n := protowire.ConsumeBytes(buf)
		if n < 0 {
			return buf, protobufError(n)
		}
		var err error
		for len(data) != 0 {
			var val int64
			if data, err = protoReadInt64(data, &val); err != nil {
				return buf, nil
			}
			*result = append(*result, val)
		}
		return buf[n:], nil
	}

func protoReadTag(buf []byte) (protowire.Number, protowire.Type, []byte, error) {
	f, t, n := protowire.ConsumeTag(buf)
	if n < 0 {
		return 0, 0, buf, protobufError(n)
	}
	return f, t, buf[n:], nil
}
*/

func protoSkipField(buf []byte, tag uint64) int {
	f, t := protowire.DecodeTag(tag)
	return protowire.ConsumeFieldValue(f, t, buf)
}

func protobufUnmarshalPoint(buf []byte, m *point) error {
	m.Reset()
	for len(buf) != 0 {
		tag, n := protowire.ConsumeVarint(buf)
		if n < 0 {
			return protobufError(n)
		}
		buf = buf[n:]
		switch tag {
		case protowire.EncodeTag(1, 0):
			res, n := protoReadUint32(buf)
			if n < 0 {
				return protobufError(n)
			}
			buf = buf[n:]
			m.x = res
			continue
		case protowire.EncodeTag(2, 0):
			res, n := protoReadUint32(buf)
			if n < 0 {
				return protobufError(n)
			}
			buf = buf[n:]
			m.y = res
			continue
		case protowire.EncodeTag(3, 0):
			res, n := protoReadUint32(buf)
			if n < 0 {
				return protobufError(n)
			}
			buf = buf[n:]
			m.z = res
			continue
		default:
			n = protoSkipField(buf, tag)
			if n < 0 {
				return protobufError(n)
			}
		}
		buf = buf[n:]
	}
	return nil
}

func protobufUnmarshalPointOptimistic(buf []byte, m *point) error {
	m.Reset()
	var tag uint64
	var n int
	var res uint32
	if len(buf) == 0 {
		return nil
	}
	tag, n = protowire.ConsumeVarint(buf)
	if n < 0 {
		return protobufError(n)
	}
	buf = buf[n:]
	if tag == protowire.EncodeTag(1, 0) {
		res, n = protoReadUint32(buf)
		if n < 0 {
			return protobufError(n)
		}
		buf = buf[n:]
		m.x = res

		if len(buf) == 0 {
			return nil
		}
		tag, n = protowire.ConsumeVarint(buf)
		if n < 0 {
			return protobufError(n)
		}
		buf = buf[n:]
	}
	if tag == protowire.EncodeTag(2, 0) {
		res, n = protoReadUint32(buf)
		if n < 0 {
			return protobufError(n)
		}
		buf = buf[n:]
		m.y = res

		if len(buf) == 0 {
			return nil
		}
		tag, n = protowire.ConsumeVarint(buf)
		if n < 0 {
			return protobufError(n)
		}
		buf = buf[n:]
	}
	if tag == protowire.EncodeTag(3, 0) {
		res, n = protoReadUint32(buf)
		if n < 0 {
			return protobufError(n)
		}
		buf = buf[n:]
		m.z = res

		// we need code below otherwise we cannot parse objects with excess fields
		// this code does not affect performance of reading object without excess fields
		if len(buf) == 0 {
			return nil
		}
		tag, n = protowire.ConsumeVarint(buf)
		if n < 0 {
			return protobufError(n)
		}
		buf = buf[n:]
	}
	if tag == protowire.EncodeTag(4, 0) {
		_, n = protoReadUint32(buf)
		if n < 0 {
			return protobufError(n)
		}
		buf = buf[n:]

		if len(buf) == 0 {
			return nil
		}
	}
	// we do not want to bench slow path accidentally, we have separate bench for that
	// data given to this function must be readable by fast path
	return fmt.Errorf("slow path")
}

func protobufAppendPoint(buf []byte, m *point, writeExcessField bool) []byte {
	initial := len(buf)
	buf = append(buf, 0)
	if m.x != 0 {
		buf = append(buf, byte(protowire.EncodeTag(1, 0))) // for large field num, must appedn 2 bytes
		// buf = protowire.AppendVarint(buf, protowire.EncodeTag(1, 0))
		buf = protowire.AppendVarint(buf, uint64(m.x))
	}
	if m.y != 0 {
		buf = append(buf, byte(protowire.EncodeTag(2, 0))) // for large field num, must appedn 2 bytes
		// buf = protowire.AppendVarint(buf, protowire.EncodeTag(2, 0))
		buf = protowire.AppendVarint(buf, uint64(m.y))
	}
	if m.z != 0 {
		buf = append(buf, byte(protowire.EncodeTag(3, 0))) // for large field num, must appedn 2 bytes
		// buf = protowire.AppendVarint(buf, protowire.EncodeTag(3, 0))
		buf = protowire.AppendVarint(buf, uint64(m.z))
	}
	if writeExcessField {
		buf = append(buf, byte(protowire.EncodeTag(4, 0))) // for large field num, must appedn 2 bytes
		// buf = protowire.AppendVarint(buf, protowire.EncodeTag(4, 0))
		buf = protowire.AppendVarint(buf, uint64(0))
	}
	buf[initial] = byte(len(buf) - initial - 1)
	return buf
}
