// Code generated by tl2gen; DO NOT EDIT.
package meta

// meta contains all types, and changes when any of them changes
// You probably want to import metamini instead.

import (
	"github.com/VKCOM/tl/internal/speed/speed_tl/internal/metainternal"
)

func SchemaGenerator() string { return "(devel)" }
func SchemaURL() string       { return "" }
func SchemaCommit() string    { return "" }
func SchemaTimestamp() uint32 { return 0 }

type Object = metainternal.Object
type Function = metainternal.Function
type TLItem = metainternal.TLItem

// deterministic order, depends on order of package init()
// we see no benefits in sorting this.
func GetAllTLItems() []TLItem {
	return metainternal.ItemsOrdered
}

// for quick one-liners
func GetTLName(tag uint32, notFoundName string) string {
	if item := FactoryItemByTLTag(tag); item != nil {
		return item.TLName()
	}
	return notFoundName
}

func FactoryItemByTLTag(tag uint32) TLItem {
	if item, ok := metainternal.ItemsByTag[tag]; ok {
		return item
	}
	return nil
}

func FactoryItemByTLName(name string) TLItem {
	if item, ok := metainternal.ItemsByName[name]; ok {
		return item
	}
	return nil
}

func init() {
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "memcache.longvalue", Tag: 0x09729c42, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "memcache.longvalueWithTime", Tag: 0x01dcd5d5, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "memcache.not_found", Tag: 0x32c42422, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "memcache.strvalue", Tag: 0xa6bebb1a, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "memcache.strvalueWithDelay", Tag: 0x1bbf7044, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "memcache.strvalueWithTime", Tag: 0xa064c821, HaTL1: true, HaTL2: true})
	metainternal.FillObject(&metainternal.TLItemImpl{Name: "memcache.Value", HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "memcache.values", Tag: 0xc894cef8, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "partialPoint", Tag: 0xbfa57042, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "partialPoints", Tag: 0x0d7f74de, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "point", Tag: 0x8ec1a27e, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "points", Tag: 0xebf9dd56, HaTL1: true, HaTL2: true})
	metainternal.FillObject(&metainternal.TLItemImpl{Name: "UnionPoint", HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "unionPointError", Tag: 0xa8dbfd23, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "unionPointValue", Tag: 0xbee8f76b, HaTL1: true, HaTL2: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "unionPoints", Tag: 0xa8495345, HaTL1: true, HaTL2: true})
}
