// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package meta

// meta contains all types, and changes when any of them changes
// You probably want to import metamini instead.

import (
	"github.com/VKCOM/tl/internal/tlast/gentlo/internal/metainternal"
)

func SchemaGenerator() string { return "(devel)" }
func SchemaURL() string       { return "" }
func SchemaCommit() string    { return "" }
func SchemaTimestamp() uint32 { return 0 }

type Object = metainternal.Object
type Function = metainternal.Function
type TLItem = metainternal.TLItem

// deterministic order, depends on order of package init()
// we see no benefits in sorting this.
func GetAllTLItems() []TLItem {
	return metainternal.ItemsOrdered
}

// for quick one-liners
func GetTLName(tag uint32, notFoundName string) string {
	if item := FactoryItemByTLTag(tag); item != nil {
		return item.TLName()
	}
	return notFoundName
}

func FactoryItemByTLTag(tag uint32) TLItem {
	if item, ok := metainternal.ItemsByTag[tag]; ok {
		return item
	}
	return nil
}

func FactoryItemByTLName(name string) TLItem {
	if item, ok := metainternal.ItemsByName[name]; ok {
		return item
	}
	return nil
}

func init() {
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.arg", Tag: 0x29dfe61b, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.array", Tag: 0xd9fb20de, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.combinator", Tag: 0x5c0a1ed5, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.combinatorLeft", Tag: 0x4c12c6d9, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.combinatorLeftBuiltin", Tag: 0xcd211f63, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.combinatorRight", Tag: 0x2c064372, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.combinator_v4", Tag: 0xe91692d5, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.exprNat", Tag: 0xdcb49bd8, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.exprType", Tag: 0xecc9da78, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.natConst", Tag: 0x8ce940b1, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.natVar", Tag: 0x4e8a14f0, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.schema_v2", Tag: 0x3a2f9be2, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.schema_v3", Tag: 0xe4a8604b, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.schema_v4", Tag: 0x90ac88d7, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.type", Tag: 0x12eb4386, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.typeExpr", Tag: 0xc1863d08, HaTL1: true})
	metainternal.FillObject(
		&metainternal.TLItemImpl{Name: "tls.typeVar", Tag: 0x0142ceae, HaTL1: true})
}
