// Code generated by qtc from "qt_constants.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package gengo

import "fmt"

import "cmp"

import "golang.org/x/exp/slices"

import "github.com/vkcom/tl/internal/tlast"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (gen *genGo) streamgenerateConstants(qw422016 *qt422016.Writer, commentString, pkgName string) {
	qw422016.N().S(commentString)
	qw422016.N().S(`
package `)
	qw422016.N().S(pkgName)
	qw422016.N().S(`
`)
	type Line struct {
		conName tlast.TL2TypeName
		magic   uint32
	}
	var lines []Line
	for _, c := range gen.kernel.TL1() {
		if c.Crc32() == 0 || c.Construct.Name.String() == "_" { // TODO - remove second check after ReqResult removed from combined.tl
			continue
		}
		exclArg, _, _ := gen.kernel.CheckExclamationWrapper(c)
		if exclArg == nil && !slices.Contains([]string{"resultTrue", "resultFalse"}, c.Construct.Name.String()) {
			continue
		}
		lines = append(lines, Line{conName: tlast.TL2TypeName(c.Construct.Name), magic: c.Crc32()})
	}
	for _, combinator := range gen.kernel.TL2() {
		if combinator.IsFunction && combinator.FuncDecl.Magic != 0 {
			lines = append(lines, Line{conName: combinator.ReferenceName(), magic: combinator.FuncDecl.Magic})
		}
		if !combinator.IsFunction && combinator.TypeDecl.Magic != 0 {
			lines = append(lines, Line{conName: combinator.ReferenceName(), magic: combinator.TypeDecl.Magic})
		}
	}
	slices.SortStableFunc(lines, func(a, b Line) int {
		return cmp.Compare(a.conName.String(), b.conName.String())
	})

	qw422016.N().S(`
// contains only constants for types not generated by tlgen.
// for generated types use tlmemcache.Get{}.TLTag()

const (
`)
	for _, c := range lines {
		qw422016.N().S(`        `)
		qw422016.N().S(canonicalGoName2(c.conName, ""))
		qw422016.N().S(` = `)
		qw422016.N().S(fmt.Sprintf("%#08x", c.magic))
		qw422016.N().S(` // `)
		qw422016.N().S(c.conName.String())
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`)
`)
}

func (gen *genGo) writegenerateConstants(qq422016 qtio422016.Writer, commentString, pkgName string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	gen.streamgenerateConstants(qw422016, commentString, pkgName)
	qt422016.ReleaseWriter(qw422016)
}

func (gen *genGo) generateConstants(commentString, pkgName string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	gen.writegenerateConstants(qb422016, commentString, pkgName)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
