// Code generated by qtc from "qt_factory.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package gengo

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (gen *genGo) streamgenerateFactory(qw422016 *qt422016.Writer, sortedImports []string, directImports *DirectImports, bytesVersion bool) {
	bytesStr := addBytes("", bytesVersion)

	qw422016.N().S(`
`)
	qw422016.N().S(HeaderComment)
	qw422016.N().S(`
package `)
	qw422016.N().S(FactoryGoPackageName)
	qw422016.N().S(addBytesLower("", bytesVersion))
	qw422016.N().S(`

import (
    "`)
	qw422016.N().S(gen.MetaPackageName)
	qw422016.N().S(`"
`)
	for _, wr := range sortedImports {
		qw422016.N().S(`    "`)
		qw422016.N().S(gen.options.Go.TLPackageNameFull)
		qw422016.N().S(`/`)
		qw422016.N().S(wr)
		qw422016.N().S(`"
`)
	}
	qw422016.N().S(`)

func CreateFunction(tag uint32) meta.Function {
    item := meta.FactoryItemByTLTag(tag)
    if item == nil || !item.IsFunction() {
        return nil
    }
    return item.CreateFunction`)
	qw422016.N().S(bytesStr)
	qw422016.N().S(`()
}

func CreateObject(tag uint32) meta.Object {
    item := meta.FactoryItemByTLTag(tag)
    if item == nil {
        return nil
    }
    return item.CreateObject`)
	qw422016.N().S(bytesStr)
	qw422016.N().S(`()
}

func CreateFunctionFromName(name string) meta.Function {
    item := meta.FactoryItemByTLName(name)
    if item == nil || !item.IsFunction() {
        return nil
    }
    return item.CreateFunction`)
	qw422016.N().S(bytesStr)
	qw422016.N().S(`()
}

func CreateObjectFromName(name string) meta.Object {
    item := meta.FactoryItemByTLName(name)
    if item == nil {
        return nil
    }
    return item.CreateObject`)
	qw422016.N().S(bytesStr)
	qw422016.N().S(`()
}

func init() {
`)
	tl1Wrappers, tl2Wrappers := gen.ExtractTopLevelTypes()

	if len(tl1Wrappers) != 0 {
		qw422016.N().S(`// TL
`)
	}
	for _, wr := range tl1Wrappers {
		hasBytes := wr.wantsBytesVersion && wr.hasBytesVersion

		if bytesVersion && !hasBytes {
			continue
		}
		if fun, ok := wr.trw.(*TypeRWStruct); ok {
			if wr.unionParent != nil && wr.unionParent.IsEnum {
				qw422016.N().S(`            meta.SetGlobalFactoryCreateForEnumElement(`)
				qw422016.N().Q(wr.tlName.String())
				qw422016.N().S(`)
`)
				continue
			}
			qw422016.N().S(`    `)
			if fun.ResultType != nil {
				qw422016.N().S(`meta.SetGlobalFactoryCreateForFunction`)
				qw422016.N().S(bytesStr)
				qw422016.N().S(`(`)
				qw422016.N().Q(wr.tlName.String())
				qw422016.N().S(`,func() meta.Function { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(bytesVersion, directImports, nil, false, true))
				qw422016.N().S(`; return &ret },`)
				if wr.WrLong != nil {
					qw422016.N().S(`func() meta.Function { var ret`)
					qw422016.N().S(` `)
					qw422016.N().S(wr.WrLong.TypeString2(bytesVersion, directImports, nil, false, true))
					qw422016.N().S(`; return &ret },`)
				} else {
					qw422016.N().S(`nil,`)
				}
			} else {
				qw422016.N().S(`meta.SetGlobalFactoryCreateForObject`)
				qw422016.N().S(bytesStr)
				qw422016.N().S(`(`)
				qw422016.N().Q(wr.tlName.String())
				qw422016.N().S(`,func() meta.Object { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(bytesVersion, directImports, nil, false, true))
				qw422016.N().S(`; return &ret }`)
			}
			qw422016.N().S(`)`)
			qw422016.N().S(`
`)
		}
	}
	if len(tl2Wrappers) != 0 {
		qw422016.N().S(`// TL2
`)
	}
	for _, wr := range tl2Wrappers {
		hasBytes := wr.wantsBytesVersion && wr.hasBytesVersion

		if bytesVersion && !hasBytes {
			continue
		}
		if fun, ok := wr.trw.(*TypeRWStruct); ok {
			if wr.unionParent != nil {
				continue
			}
			qw422016.N().S(`    `)
			if fun.ResultType != nil {
				qw422016.N().S(`meta.SetGlobalFactoryCreateForFunction`)
				qw422016.N().S(bytesStr)
				qw422016.N().S(`(`)
				qw422016.N().Q(wr.tlName.String())
				qw422016.N().S(`,func() meta.Function { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(bytesVersion, directImports, nil, false, true))
				qw422016.N().S(`; return &ret },`)
				if wr.WrLong != nil {
					qw422016.N().S(`func() meta.Function { var ret`)
					qw422016.N().S(` `)
					qw422016.N().S(wr.WrLong.TypeString2(bytesVersion, directImports, nil, false, true))
					qw422016.N().S(`; return &ret },`)
				} else {
					qw422016.N().S(`nil,`)
				}
			} else {
				qw422016.N().S(`meta.SetGlobalFactoryCreateForObject`)
				qw422016.N().S(bytesStr)
				qw422016.N().S(`(`)
				qw422016.N().Q(wr.tlName.String())
				qw422016.N().S(`,func() meta.Object { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(bytesVersion, directImports, nil, false, true))
				qw422016.N().S(`; return &ret }`)
			}
			qw422016.N().S(`)`)
			qw422016.N().S(`
`)
		}
		if _, ok := wr.trw.(*TypeRWUnion); ok {
			qw422016.N().S(`    `)
			qw422016.N().S(`meta.SetGlobalFactoryCreateForObject`)
			qw422016.N().S(bytesStr)
			qw422016.N().S(`(`)
			qw422016.N().Q(wr.tlName.String())
			qw422016.N().S(`,func() meta.Object { var ret`)
			qw422016.N().S(` `)
			qw422016.N().S(wr.TypeString2(bytesVersion, directImports, nil, false, true))
			qw422016.N().S(`; return &ret })`)
			qw422016.N().S(`
`)
		}
	}
	qw422016.N().S(`}

`)
}

func (gen *genGo) writegenerateFactory(qq422016 qtio422016.Writer, sortedImports []string, directImports *DirectImports, bytesVersion bool) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	gen.streamgenerateFactory(qw422016, sortedImports, directImports, bytesVersion)
	qt422016.ReleaseWriter(qw422016)
}

func (gen *genGo) generateFactory(sortedImports []string, directImports *DirectImports, bytesVersion bool) string {
	qb422016 := qt422016.AcquireByteBuffer()
	gen.writegenerateFactory(qb422016, sortedImports, directImports, bytesVersion)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
