// Code generated by qtc from "qt_meta.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package gengo

import "fmt"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (gen *genGo) streamgenerateMetaMini(qw422016 *qt422016.Writer, tlgenVersion string) {
	qw422016.N().S(HeaderComment)
	qw422016.N().S(`
package `)
	qw422016.E().S(MetaGoPackageName)
	qw422016.N().S(`mini

// metamini contains only types which are already imported by your app
// So GetTLName will work for types you need, and at the same type your
// code will not depend on many types you do not need.

import (
    "`)
	qw422016.N().S(gen.options.Go.TLPackageNameFull)
	qw422016.N().S(`/internal/metainternal"
)

type Object = metainternal.Object
type Function = metainternal.Function
type TLItem = metainternal.TLItem

// deterministic order, depends on order of package init()
// we see no benefits in sorting this.
func GetAllTLItems() []TLItem {
	return metainternal.ItemsOrdered
}

// for quick one-liners
func GetTLName(tag uint32, notFoundName string) string {
	if item := FactoryItemByTLTag(tag); item != nil {
		return item.TLName()
	}
	return notFoundName
}

func FactoryItemByTLTag(tag uint32) TLItem {
    if item, ok := metainternal.ItemsByTag[tag]; ok {
        return item
    }
    return nil
}

func FactoryItemByTLName(name string) TLItem {
    if item, ok := metainternal.ItemsByName[name]; ok {
        return item
    }
    return nil
}

`)
}

func (gen *genGo) writegenerateMetaMini(qq422016 qtio422016.Writer, tlgenVersion string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	gen.streamgenerateMetaMini(qw422016, tlgenVersion)
	qt422016.ReleaseWriter(qw422016)
}

func (gen *genGo) generateMetaMini(tlgenVersion string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	gen.writegenerateMetaMini(qb422016, tlgenVersion)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (gen *genGo) streamgenerateMeta(qw422016 *qt422016.Writer, tlgenVersion string) {
	qw422016.N().S(HeaderComment)
	qw422016.N().S(`
package `)
	qw422016.E().S(MetaGoPackageName)
	qw422016.N().S(`

// meta contains all types, and changes when any of them changes
// You probably want to import metamini instead.

import (
    "`)
	qw422016.N().S(gen.options.Go.TLPackageNameFull)
	qw422016.N().S(`/internal/metainternal"
)

func SchemaGenerator() string { return `)
	qw422016.N().S(fmt.Sprintf("%#v", tlgenVersion))
	qw422016.N().S(` }
func SchemaURL() string { return `)
	qw422016.N().S(fmt.Sprintf("%#v", gen.options.SchemaURL))
	qw422016.N().S(` }
func SchemaCommit() string { return `)
	qw422016.N().S(fmt.Sprintf("%#v", gen.options.SchemaCommit))
	qw422016.N().S(` }
func SchemaTimestamp() uint32 { return `)
	qw422016.E().V(gen.options.SchemaTimestamp)
	qw422016.N().S(` }

type Object = metainternal.Object
type Function = metainternal.Function
type TLItem = metainternal.TLItem

// deterministic order, depends on order of package init()
// we see no benefits in sorting this.
func GetAllTLItems() []TLItem {
	return metainternal.ItemsOrdered
}

// for quick one-liners
func GetTLName(tag uint32, notFoundName string) string {
	if item := FactoryItemByTLTag(tag); item != nil {
		return item.TLName()
	}
	return notFoundName
}

func FactoryItemByTLTag(tag uint32) TLItem {
    if item, ok := metainternal.ItemsByTag[tag]; ok {
        return item
    }
    return nil
}

func FactoryItemByTLName(name string) TLItem {
    if item, ok := metainternal.ItemsByName[name]; ok {
        return item
    }
    return nil
}

`)
}

func (gen *genGo) writegenerateMeta(qq422016 qtio422016.Writer, tlgenVersion string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	gen.streamgenerateMeta(qw422016, tlgenVersion)
	qt422016.ReleaseWriter(qw422016)
}

func (gen *genGo) generateMeta(tlgenVersion string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	gen.writegenerateMeta(qb422016, tlgenVersion)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (gen *genGo) streamgenerateMetaInit(qw422016 *qt422016.Writer, addHeader bool, types []*TypeRWWrapper, forNamespace func(ns string) bool, hasTypes *bool, packageNames string) {
	if addHeader {
		qw422016.N().S(`    `)
		qw422016.N().S(HeaderComment)
		qw422016.N().S(`
    package `)
		qw422016.E().S(packageNames)
		qw422016.N().S(`
    import (
        "`)
		qw422016.N().S(gen.options.Go.TLPackageNameFull)
		qw422016.N().S(`/internal/metainternal"
    )

`)
	}
	qw422016.N().S(`
func init() {
`)
	for _, wr := range types {
		if !forNamespace(wr.tlName.Namespace) {
			continue
		}
		if !wr.pureType.Common().IsTopLevel() {
			continue
		}
		argumentsTypesContainUnionTypes := wr.DoArgumentsContainUnionTypes()

		if fun, ok := wr.trw.(*TypeRWStruct); ok {
			if hasTypes != nil {
				*hasTypes = true
			}
			resultTypeContainsUnionTypes := false

			if fun.ResultType != nil {
				resultTypeContainsUnionTypes = fun.wr.DoesReturnTypeContainUnionTypes()

				qw422016.N().S(`        metainternal.FillFunction`)
			} else {
				qw422016.N().S(`metainternal.FillObject`)
			}
			qw422016.N().S(`(
        &metainternal.TLItemImpl{Name: "`)
			qw422016.N().S(wr.tlName.String())
			qw422016.N().S(`"`)

			if wr.tlTag != 0 {
				qw422016.N().S(`, Tag: `)
				qw422016.N().S(fmt.Sprintf("0x%08x", wr.tlTag))
			}
			if !wr.originateFromTL2 {
				qw422016.N().S(`, HaTL1:true`)
			}
			if wr.HasTL2() {
				qw422016.N().S(`, HaTL2:true`)
			}
			if wr.AnnotationsMask() != 0 {
				qw422016.N().S(`, Annotations: `)
				qw422016.N().S(fmt.Sprintf("0x%x", wr.AnnotationsMask()))
			}
			if argumentsTypesContainUnionTypes {
				qw422016.N().S(`, ArgumentsTypesContainUnionTypes:true`)
			}
			if resultTypeContainsUnionTypes {
				qw422016.N().S(`, ResultTypeContainsUnionTypes:true`)
			}
			qw422016.N().S(`})
`)
		}
		if union, ok := wr.trw.(*TypeRWUnion); ok && union.wr.HasTL2() {
			if hasTypes != nil {
				*hasTypes = true
			}
			// unions are not top level types by TL1 rules, but we make them so by implementing Read/Write as ReadBoxed/WriteBoxed

			qw422016.N().S(`        metainternal.FillObject(&metainternal.TLItemImpl{Name: "`)
			qw422016.N().S(wr.tlName.String())
			qw422016.N().S(`"`)

			if wr.tlTag != 0 {
				qw422016.N().S(`, Tag: `)
				qw422016.N().S(fmt.Sprintf("0x%08x", wr.tlTag))
			}
			if !wr.originateFromTL2 {
				qw422016.N().S(`, HaTL1:true`)
			}
			if wr.HasTL2() {
				qw422016.N().S(`, HaTL2:true`)
			}
			if wr.AnnotationsMask() != 0 {
				qw422016.N().S(`, Annotations: `)
				qw422016.N().S(fmt.Sprintf("0x%x", wr.AnnotationsMask()))
			}
			if argumentsTypesContainUnionTypes {
				qw422016.N().S(`, ArgumentsTypesContainUnionTypes:true`)
			}
			qw422016.N().S(`})
`)
		}
	}
	qw422016.N().S(`}
`)
}

func (gen *genGo) writegenerateMetaInit(qq422016 qtio422016.Writer, addHeader bool, types []*TypeRWWrapper, forNamespace func(ns string) bool, hasTypes *bool, packageNames string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	gen.streamgenerateMetaInit(qw422016, addHeader, types, forNamespace, hasTypes, packageNames)
	qt422016.ReleaseWriter(qw422016)
}

func (gen *genGo) generateMetaInit(addHeader bool, types []*TypeRWWrapper, forNamespace func(ns string) bool, hasTypes *bool, packageNames string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	gen.writegenerateMetaInit(qb422016, addHeader, types, forNamespace, hasTypes, packageNames)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
