// Code generated by qtc from "qt_struct.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package gengo

import "fmt"

import "github.com/VKCOM/tl/internal/utils"

import "strings"

import "sort"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (struct_ *TypeRWStruct) StreamGenerateCode(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	goName := addBytes(struct_.wr.goGlobalName, bytesVersion)
	tlTag := fmt.Sprintf("0x%08x", struct_.wr.tlTag)
	tlName := struct_.wr.tlName.String()
	natArgsDecl := struct_.wr.formatNatArgsDecl()
	natArgsCall := struct_.wr.formatNatArgsDeclCall()
	writeNeedsError := struct_.wr.hasErrorInWriteMethods

	if struct_.unionParent != nil {
		ep := struct_.unionParent.wr.TypeString2(bytesVersion, directImports, struct_.wr.ins, false, false)

		if struct_.unionParent.IsEnum {
			qw422016.N().S(`func `)
			qw422016.N().S(goName)
			qw422016.N().S(`() `)
			qw422016.N().S(ep)
			qw422016.N().S(` { return `)
			qw422016.N().S(ep)
			qw422016.N().S(`__MakeEnum(`)
			qw422016.N().D(struct_.unionIndex)
			qw422016.N().S(`) }
`)
			return
		} else {
			qw422016.N().S(`func (item `)
			qw422016.N().S(goName)
			qw422016.N().S(`) AsUnion() `)
			qw422016.N().S(ep)
			qw422016.N().S(` {
    var ret `)
			qw422016.N().S(ep)
			qw422016.N().S(`
    ret.Set`)
			qw422016.N().S(struct_.unionParent.Fields[struct_.unionIndex].goName)
			qw422016.N().S(`(`)
			qw422016.N().S(ifString(struct_.wr.IsTrueType(), "", "item"))
			qw422016.N().S(`)
    return ret
}

`)
		}
	}
	struct_.streamtypeDefinition(qw422016, bytesVersion, directImports)
	qw422016.N().S(`
`)
	if struct_.wr.tlTag != 0 || struct_.wr.originateFromTL2 {
		// anonymous square brackets citizens or other exotic type

		qw422016.N().S(`func (`)
		qw422016.N().S(goName)
		qw422016.N().S(`) TLName() string { return `)
		qw422016.N().Q(tlName)
		qw422016.N().S(` }
func (`)
		qw422016.N().S(goName)
		qw422016.N().S(`) TLTag() uint32  { return `)
		qw422016.N().S(tlTag)
		qw422016.N().S(` }

`)
	}
	qw422016.N().S(`    `)
	struct_.streamfieldMaskGettersAndSetters(qw422016, bytesVersion, directImports)
	qw422016.N().S(`
func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) Reset() { `)
	struct_.streamresetFields(qw422016, bytesVersion, directImports)
	qw422016.N().S(` }

`)
	if struct_.wr.gen.options.GenerateRandomCode {
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) FillRandom(rg *basictl.RandGenerator`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(`) { `)
		struct_.streamrandomFields(qw422016, bytesVersion, directImports)
		qw422016.N().S(` }
`)
	}
	qw422016.N().S(`
`)
	if struct_.wr.hasRepairMasks {
		qw422016.N().S(`func (item `)
		qw422016.N().S(goName)
		qw422016.N().S(`) RepairMasksValue(`)
		qw422016.N().S(strings.TrimPrefix(natArgsDecl, ","))
		qw422016.N().S(`) `)
		qw422016.N().S(goName)
		qw422016.N().S(` {
    item.RepairMasks(`)
		qw422016.N().S(strings.TrimPrefix(natArgsCall, ","))
		qw422016.N().S(`)
    return item
}
func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) RepairMasks(`)
		qw422016.N().S(strings.TrimPrefix(natArgsDecl, ","))
		qw422016.N().S(`) {
`)
		for _, tl2mask := range struct_.AllNewTL2Masks() {
			qw422016.N().S(`         item.`)
			qw422016.N().S(tl2mask)
			qw422016.N().S(` = 0
`)
		}
		for _, field := range struct_.Fields {
			if field.IsTL2Omitted() {
				continue
			}
			fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

			if field.MaskTL2Bit() != nil && field.FieldMask() != nil {
				qw422016.N().S(`            if `)
				qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
				qw422016.N().S(` & (1<<`)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`) != 0 {
                item.`)
				qw422016.N().S(field.TL2MaskForOP("|="))
				qw422016.N().S(`
            }
`)
			}
			repairCode := field.t.TypeRepairMasksCode(bytesVersion, directImports, struct_.wr.ins, fieldAccess, formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk)

			if !field.IsBit() && field.t.hasRepairMasks {
				if field.recursive {
					qw422016.N().S(`                if `)
					qw422016.N().S(fieldAccess)
					qw422016.N().S(` != nil {
                    `)
					qw422016.N().S(repairCode)
					qw422016.N().S(`
                }
`)
				} else {
					qw422016.N().S(`                `)
					qw422016.N().S(repairCode)
					qw422016.N().S(`
`)
				}
			}
		}
		qw422016.N().S(`}
`)
	}
	qw422016.N().S(`
`)
	if struct_.wr.gen.options.Go.GenerateLegacyReadWrite {
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) Read(w []byte`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(struct_.wr.fetcherDecl())
		qw422016.N().S(`) (_ []byte, err error) {
    return item.ReadTL1(w`)
		qw422016.N().S(natArgsCall)
		qw422016.N().S(struct_.wr.fetcherCall())
		qw422016.N().S(`)
}
`)
	}
	qw422016.N().S(`func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) ReadTL1(w []byte `)
	qw422016.N().S(natArgsDecl)
	qw422016.N().S(struct_.wr.fetcherDecl())
	qw422016.N().S(`) (_ []byte, err error) { `)
	struct_.streamreadFields(qw422016, bytesVersion, directImports)
	qw422016.N().S(` }

`)
	if len(struct_.wr.NatParams) == 0 && !struct_.wr.HasFetcher() {
		if struct_.wr.gen.options.Go.GenerateLegacyReadWrite {
			qw422016.N().S(`func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) WriteGeneral(w []byte`)
			qw422016.N().S(natArgsDecl)
			qw422016.N().S(`) (_ []byte, err error) {
    return item.WriteTL1General(w`)
			qw422016.N().S(natArgsCall)
			qw422016.N().S(`)
}
`)
		}
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) WriteTL1General(w []byte`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(`) (_ []byte, err error) {
`)
		if struct_.wr.originateFromTL2 {
			qw422016.N().S(`    return w, basictl.TL2Error("not implemented for tl2 type")
`)
		} else {
			qw422016.N().S(`    return item.WriteTL1(w`)
			qw422016.N().S(natArgsCall)
			qw422016.N().S(`)`)
			if !writeNeedsError {
				qw422016.N().S(`, nil`)
			}
		}
		qw422016.N().S(`}
`)
	}
	qw422016.N().S(`
`)
	if struct_.wr.gen.options.Go.GenerateLegacyReadWrite {
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) Write(w []byte`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(struct_.wr.fetcherDecl())
		qw422016.N().S(`) `)
		qw422016.N().S(wrapWithError(writeNeedsError, "[]byte"))
		qw422016.N().S(` {
    return item.WriteTL1(w`)
		qw422016.N().S(natArgsCall)
		qw422016.N().S(struct_.wr.fetcherCall())
		qw422016.N().S(`)
}
`)
	}
	qw422016.N().S(`func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) WriteTL1(w []byte`)
	qw422016.N().S(natArgsDecl)
	qw422016.N().S(struct_.wr.fetcherDecl())
	qw422016.N().S(`) `)
	qw422016.N().S(wrapWithError(writeNeedsError, "[]byte"))
	qw422016.N().S(` { `)
	struct_.streamwriteFields(qw422016, bytesVersion, directImports)
	qw422016.N().S(` }

`)
	if struct_.wr.tlTag != 0 || struct_.wr.originateFromTL2 {
		if struct_.wr.gen.options.Go.GenerateLegacyReadWrite {
			qw422016.N().S(`func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) ReadBoxed(w []byte`)
			qw422016.N().S(natArgsDecl)
			qw422016.N().S(struct_.wr.fetcherDecl())
			qw422016.N().S(`) (_ []byte, err error) {
    return item.ReadTL1Boxed(w`)
			qw422016.N().S(natArgsCall)
			qw422016.N().S(struct_.wr.fetcherCall())
			qw422016.N().S(`)
}
`)
		}
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadTL1Boxed(w []byte`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(struct_.wr.fetcherDecl())
		qw422016.N().S(`) (_ []byte, err error) {
`)
		if struct_.wr.originateFromTL2 {
			qw422016.N().S(`    return w, basictl.TL2Error("not implemented for tl2 type")
`)
		} else {
			qw422016.N().S(`    if w, err = basictl.NatReadExactTag(w, `)
			qw422016.N().S(tlTag)
			qw422016.N().S(`); err != nil {
        return w, err
    }
    return item.ReadTL1(w`)
			qw422016.N().S(natArgsCall)
			qw422016.N().S(struct_.wr.fetcherCall())
			qw422016.N().S(`)
`)
		}
		qw422016.N().S(`}

`)
		if len(struct_.wr.NatParams) == 0 && !struct_.wr.HasFetcher() {
			if struct_.wr.gen.options.Go.GenerateLegacyReadWrite {
				qw422016.N().S(`func (item *`)
				qw422016.N().S(goName)
				qw422016.N().S(`) WriteBoxedGeneral(w []byte`)
				qw422016.N().S(natArgsDecl)
				qw422016.N().S(`) (_ []byte, err error) {
    return item.WriteTL1BoxedGeneral(w`)
				qw422016.N().S(natArgsCall)
				qw422016.N().S(`)
}
`)
			}
			qw422016.N().S(`func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) WriteTL1BoxedGeneral(w []byte`)
			qw422016.N().S(natArgsDecl)
			qw422016.N().S(`) (_ []byte, err error) {
`)
			if struct_.wr.originateFromTL2 {
				qw422016.N().S(`    return w, basictl.TL2Error("not implemented for tl2 type")
`)
			} else {
				qw422016.N().S(`    return item.WriteTL1Boxed(w`)
				qw422016.N().S(natArgsCall)
				qw422016.N().S(`)`)
				if !writeNeedsError {
					qw422016.N().S(`, nil`)
				}
			}
			qw422016.N().S(`}
`)
		}
		qw422016.N().S(`
`)
		if struct_.wr.gen.options.Go.GenerateLegacyReadWrite {
			qw422016.N().S(`func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) WriteBoxed(w []byte`)
			qw422016.N().S(natArgsDecl)
			qw422016.N().S(struct_.wr.fetcherDecl())
			qw422016.N().S(`) `)
			qw422016.N().S(wrapWithError(writeNeedsError, "[]byte"))
			qw422016.N().S(` {
    return item.WriteTL1Boxed(w`)
			qw422016.N().S(natArgsCall)
			qw422016.N().S(struct_.wr.fetcherCall())
			qw422016.N().S(`)
}
`)
		}
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) WriteTL1Boxed(w []byte`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(struct_.wr.fetcherDecl())
		qw422016.N().S(`) `)
		qw422016.N().S(wrapWithError(writeNeedsError, "[]byte"))
		qw422016.N().S(` {
`)
		if struct_.wr.originateFromTL2 {
			if writeNeedsError {
				qw422016.N().S(`    return w, basictl.TL2Error("not implemented for tl2 type")
`)
			} else {
				qw422016.N().S(`    panic(basictl.TL2Error("not implemented for tl2 type"))
`)
			}
		} else {
			qw422016.N().S(`    w = basictl.NatWrite(w, `)
			qw422016.N().S(tlTag)
			qw422016.N().S(`)
    return item.WriteTL1(w`)
			qw422016.N().S(natArgsCall)
			qw422016.N().S(struct_.wr.fetcherCall())
			qw422016.N().S(`)
`)
		}
		qw422016.N().S(`}

`)
	}
	struct_.streamfunctionCode(qw422016, bytesVersion, directImports)
	qw422016.N().S(`
`)
	if len(struct_.wr.NatParams) == 0 && !struct_.wr.HasFetcher() {
		qw422016.N().S(`
func (item `)
		qw422016.N().S(goName)
		qw422016.N().S(`) String(`)
		qw422016.N().S(struct_.wr.formatNatArgsDeclNoComma())
		qw422016.N().S(`) string {
`)
		if writeNeedsError {
			qw422016.N().S(`    w, err := item.WriteJSON(nil`)
			qw422016.N().S(natArgsCall)
			qw422016.N().S(`)
    if err != nil {
        return err.Error()
    }
    return string(w)
`)
		} else {
			qw422016.N().S(`    return string(item.WriteJSON(nil`)
			qw422016.N().S(natArgsCall)
			qw422016.N().S(`))
`)
		}
		qw422016.N().S(`}
`)
	}
	struct_.streamgenerateJSONCode(qw422016, bytesVersion, directImports)
	qw422016.N().S(`
`)
	if struct_.wr.gen.options.GenerateTL2() {
		struct_.streamgenerateTL2Code(qw422016, bytesVersion, directImports)
		qw422016.N().S(`
`)
	}
}

func (struct_ *TypeRWStruct) WriteGenerateCode(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.StreamGenerateCode(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) GenerateCode(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.WriteGenerateCode(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamtypeDefinition(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	goName := addBytes(struct_.wr.goGlobalName, bytesVersion)

	qw422016.N().S(`    `)
	qw422016.N().S(printCommentsType(struct_.pureTypeStruct))

	if struct_.isAlias() || struct_.isTypedef() {
		asterisk := ifString(struct_.Fields[0].recursive, "*", "")
		fieldTypeString := struct_.Fields[0].t.TypeString2(bytesVersion, directImports, struct_.wr.ins, false, false)

		qw422016.N().S(`    `)
		qw422016.N().S(printCommentsField(struct_.Fields[0]))

		qw422016.N().S(`type `)
		qw422016.N().S(goName)
		qw422016.N().S(` `)
		qw422016.N().S(asterisk)
		qw422016.N().S(fieldTypeString)
		qw422016.N().S(`

func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ptr() *`)
		qw422016.N().S(fieldTypeString)
		qw422016.N().S(` { return (*`)
		qw422016.N().S(fieldTypeString)
		qw422016.N().S(`)(item) }
`)
		return
	}
	qw422016.N().S(`type `)
	qw422016.N().S(goName)
	qw422016.N().S(` struct {
`)
	for _, field := range struct_.Fields {
		qw422016.N().S(`        `)
		qw422016.N().S(printCommentsField(field))

		if field.IsTL2Omitted() {
			continue
		}
		asterisk := ifString(field.recursive, "*", "")
		fieldTypeString := ""
		fieldsMaskComment := ""
		if field.FieldMask() != nil {
			fieldsMaskComment = fmt.Sprintf(" // Conditional: %s.%d", formatNatArg(struct_.Fields, *field.FieldMask()), field.BitNumber())
		} else if field.MaskTL2Bit() != nil {
			fieldsMaskComment = fmt.Sprintf(" // Optional, use Set%s", field.goName)
		}
		prefixComment := ""
		if field.IsBit() {
			prefixComment = "// "
			fieldTypeString = ifString(field.t.originateFromTL2, "bit", "(TrueType)")
		} else {
			fieldTypeString = field.t.TypeString2(bytesVersion, directImports, struct_.wr.ins, false, false)
		}

		qw422016.N().S(`    `)
		qw422016.N().S(prefixComment)
		qw422016.N().S(field.goName)
		qw422016.N().S(` `)
		qw422016.N().S(asterisk)
		qw422016.N().S(fieldTypeString)
		qw422016.N().S(fieldsMaskComment)
		qw422016.N().S(`
`)
	}
	if struct_.wr.HasTL2() {
		for _, tl2mask := range struct_.AllNewTL2Masks() {
			qw422016.N().S(`             `)
			qw422016.N().S(tl2mask)
			qw422016.N().S(` byte
`)
		}
	}
	qw422016.N().S(`}
`)
}

func (struct_ *TypeRWStruct) writetypeDefinition(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamtypeDefinition(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) typeDefinition(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writetypeDefinition(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamfieldMaskGettersAndSetters(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	goName := addBytes(struct_.wr.goGlobalName, bytesVersion)

	for i, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		if field.FieldMask() == nil && field.MaskTL2Bit() == nil {
			continue
		}
		if field.FieldMask() != nil && field.FieldMask().IsNumber() {
			continue
		}
		fieldTypeString := ""
		isTrueType := "bool"
		if !field.t.IsTrueType() {
			fieldTypeString = field.t.TypeString2(bytesVersion, directImports, struct_.wr.ins, false, false)
			isTrueType = fieldTypeString
		}
		asterisk := addAsterisk(field.recursive, "")
		maskFunArg := false
		natArgUse := ""
		if field.FieldMask() != nil {
			maskFunArg = !field.FieldMask().IsField() && !field.FieldMask().IsNumber()
			natArgUse = formatNatArg(struct_.Fields, *field.FieldMask())
		}

		// Example
		//     notify.notification#461f4ce2 {mode:#} removed:mode.0?Bool = notify.Notification mode;
		//     @any notify.getScheduledNotifications#f53ad7bd  = notify.Notification 0;
		// We skip generating Set and Clear altogether in this case, but still generate IsSet
		setName := struct_.setNames[i]
		if setName == "" {
			setName = struct_.fieldsDec.deconflictName("Set" + utils.ToUpperFirst(field.goName))
			struct_.setNames[i] = setName
		}
		getName := "G" + setName[1:]

		if struct_.wr.HasTL2() && !field.IsBit() && field.FieldMask() != nil && field.FieldMask() == nil {
			qw422016.N().S(`            func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) `)
			qw422016.N().S(getName)
			qw422016.N().S(`() `)
			qw422016.N().S(asterisk)
			qw422016.N().S(isTrueType)
			qw422016.N().S(` {
                return item.`)
			qw422016.N().S(field.goName)
			qw422016.N().S(`
            }
`)
		}
		qw422016.N().S(`        func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) `)
		qw422016.N().S(setName)
		qw422016.N().S(`(v `)
		qw422016.N().S(isTrueType)
		if maskFunArg {
			qw422016.N().S(`, `)
			qw422016.N().S(natArgUse)
			qw422016.N().S(` *uint32`)
		}
		qw422016.N().S(`) {
`)
		if !field.IsBit() {
			qw422016.N().S(`            `)
			qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
			qw422016.N().S(`            `)
			qw422016.N().S(asterisk)
			qw422016.N().S(`item.`)
			qw422016.N().S(field.goName)
			qw422016.N().S(` = v
`)
		}
		if field.FieldMask() != nil {
			if maskFunArg {
				qw422016.N().S(`                if `)
				qw422016.N().S(natArgUse)
				qw422016.N().S(` != nil {
`)
			}
			if field.IsBit() {
				qw422016.N().S(`                if v {
                    `)
				qw422016.N().S(addAsterisk(maskFunArg, natArgUse))
				qw422016.N().S(` |= 1 << `)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`
                } else {
                    `)
				qw422016.N().S(addAsterisk(maskFunArg, natArgUse))
				qw422016.N().S(` &^= 1 << `)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`
                }
`)
			} else {
				qw422016.N().S(`                `)
				qw422016.N().S(addAsterisk(maskFunArg, natArgUse))
				qw422016.N().S(` |= 1 << `)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`
`)
			}
			if maskFunArg {
				qw422016.N().S(`                }
`)
			}
		}
		if field.MaskTL2Bit() != nil {
			if field.IsBit() {
				qw422016.N().S(`                if v {
                    item.`)
				qw422016.N().S(field.TL2MaskForOP("|="))
				qw422016.N().S(`
                } else {
                    item.`)
				qw422016.N().S(field.TL2MaskForOP("&^="))
				qw422016.N().S(`
                }
`)
			} else {
				qw422016.N().S(`                item.`)
				qw422016.N().S(field.TL2MaskForOP("|="))
				qw422016.N().S(`
`)
			}
		}
		qw422016.N().S(`        }
`)
		if !field.IsBit() {
			clearName := struct_.clearNames[i]
			if clearName == "" {
				clearName = struct_.fieldsDec.deconflictName("Clear" + utils.ToUpperFirst(field.goName))
				struct_.clearNames[i] = clearName
			}

			qw422016.N().S(`            func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) `)
			qw422016.N().S(clearName)
			qw422016.N().S(`(`)
			if maskFunArg {
				qw422016.N().S(natArgUse)
				qw422016.N().S(` *uint32`)
			}
			qw422016.N().S(`) {
            `)
			qw422016.N().S(field.TypeResettingCode(bytesVersion, directImports, struct_.wr.ins))
			qw422016.N().S(`
`)
			if field.FieldMask() != nil {
				if maskFunArg {
					qw422016.N().S(`                    if `)
					qw422016.N().S(natArgUse)
					qw422016.N().S(` != nil {
`)
				}
				qw422016.N().S(`                    `)
				qw422016.N().S(addAsterisk(maskFunArg, natArgUse))
				qw422016.N().S(` &^= 1 << `)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`
`)
				if maskFunArg {
					qw422016.N().S(`                    }
`)
				}
			}
			if field.MaskTL2Bit() != nil {
				qw422016.N().S(`                item.`)
				qw422016.N().S(field.TL2MaskForOP("&^="))
				qw422016.N().S(`
`)
			}
			qw422016.N().S(`            }
`)
		}
		isSetName := struct_.isSetNames[i]
		if isSetName == "" {
			isSetName = struct_.fieldsDec.deconflictName("IsSet" + utils.ToUpperFirst(field.goName))
			struct_.isSetNames[i] = isSetName
		}

		if field.MaskTL2Bit() != nil {
			qw422016.N().S(`            func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) `)
			qw422016.N().S(isSetName)
			qw422016.N().S(`() bool { return item.`)
			qw422016.N().S(field.TL2MaskForOP("&"))
			qw422016.N().S(` != 0 }
`)
		} else {
			qw422016.N().S(`            func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) `)
			qw422016.N().S(isSetName)
			qw422016.N().S(`(`)
			if maskFunArg {
				qw422016.N().S(natArgUse)
				qw422016.N().S(` uint32`)
			}
			qw422016.N().S(`) bool { return `)
			qw422016.N().S(natArgUse)
			qw422016.N().S(` & (1 << `)
			qw422016.E().V(field.BitNumber())
			qw422016.N().S(`) != 0 }
`)
		}
		qw422016.N().S(`
`)
	}
}

func (struct_ *TypeRWStruct) writefieldMaskGettersAndSetters(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamfieldMaskGettersAndSetters(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) fieldMaskGettersAndSetters(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writefieldMaskGettersAndSetters(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamgenerateJSONCode(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	goName := addBytes(struct_.wr.goGlobalName, bytesVersion)
	tlName := struct_.wr.tlName.String()
	natArgsDecl := struct_.wr.formatNatArgsDecl()
	natArgsCall := struct_.wr.formatNatArgsDeclCall()
	writeNeedsError := struct_.wr.hasErrorInWriteMethods

	if struct_.isTypedef() {
		field := struct_.Fields[0]

		if len(struct_.wr.NatParams) == 0 {
			qw422016.N().S(`func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
    jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
    return item.ReadJSONGeneral(&jctx, in)
}

`)
		}
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(`) error {
    `)
		qw422016.N().S(field.t.TypeJSON2ReadingCode(bytesVersion, directImports, struct_.wr.ins, "in", "item.ptr()", formatNatArgs(struct_.Fields, field.NatArgs()), true))
		qw422016.N().S(`
    return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(`) (_ []byte, err error) {
    return item.WriteJSONOpt(jctx, w`)
		qw422016.N().S(natArgsCall)
		qw422016.N().S(`)`)
		if !writeNeedsError {
			qw422016.N().S(`, nil`)
		}
		qw422016.N().S(`}

func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) WriteJSON(w []byte`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(`) `)
		qw422016.N().S(wrapWithError(writeNeedsError, "[]byte"))
		qw422016.N().S(` {
    return item.WriteJSONOpt(nil, w`)
		qw422016.N().S(natArgsCall)
		qw422016.N().S(`)
}

func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte`)
		qw422016.N().S(natArgsDecl)
		qw422016.N().S(`) `)
		qw422016.N().S(wrapWithError(writeNeedsError, "[]byte"))
		qw422016.N().S(` {
    `)
		qw422016.N().S(field.t.TypeJSONWritingCode(bytesVersion, directImports, struct_.wr.ins, "item.ptr()", formatNatArgs(struct_.Fields, field.NatArgs()), true, writeNeedsError))
		qw422016.N().S(`
    return w`)
		if writeNeedsError {
			qw422016.N().S(`, nil`)
		}
		qw422016.N().S(`}
`)
	} else {
		// Sorting fields is bad idea. Most efficient parsing is if they are in TL order, because no look ahead required

		qw422016.N().S(`
`)
		struct_.streamreadJSONCode(qw422016, bytesVersion, directImports)
		qw422016.N().S(`
`)
		struct_.streamwriteJSONCode(qw422016, bytesVersion, directImports)
		qw422016.N().S(`
`)
	}
	if len(struct_.wr.NatParams) == 0 {
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) MarshalJSON() ([]byte, error) {
      return item.WriteJSON(nil)`)
		if !writeNeedsError {
			qw422016.N().S(`, nil`)
		}
		qw422016.N().S(`}

func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) UnmarshalJSON(b []byte) error {
    if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
        return `)
		qw422016.N().S(struct_.wr.gen.InternalPrefix())
		qw422016.N().S(`ErrorInvalidJSON(`)
		qw422016.N().Q(tlName)
		qw422016.N().S(`, err.Error())
    }
    return nil
}
`)
	}
	qw422016.N().S(`
`)
}

func (struct_ *TypeRWStruct) writegenerateJSONCode(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamgenerateJSONCode(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) generateJSONCode(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writegenerateJSONCode(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamreadJSONCode(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	goName := addBytes(struct_.wr.goGlobalName, bytesVersion)
	tlName := struct_.wr.tlName.String()
	natArgsDecl := struct_.wr.formatNatArgsDecl()

	if len(struct_.wr.NatParams) == 0 {
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
    jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
    return item.ReadJSONGeneral(&jctx, in)
}

`)
	}
	qw422016.N().S(`func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer`)
	qw422016.N().S(natArgsDecl)
	qw422016.N().S(`) error {
`)
	if struct_.wr.HasTL2() {
		for _, tl2mask := range struct_.AllNewTL2Masks() {
			qw422016.N().S(`         item.`)
			qw422016.N().S(tl2mask)
			qw422016.N().S(` = 0
`)
		}
	}
	for _, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		qw422016.N().S(`        var prop`)
		qw422016.N().S(field.goName)
		qw422016.N().S(`Presented bool
`)
		if field.IsBit() {
			qw422016.N().S(`            var trueType`)
			qw422016.N().S(field.goName)
			qw422016.N().S(`Value     bool
`)
		} else if field.IsTypeDependsFromLocalFields() {
			qw422016.N().S(`            var raw`)
			qw422016.N().S(field.goName)
			qw422016.N().S(` []byte
`)
		}
	}
	// BLOCK: main read

	qw422016.N().S(`    if in != nil {
        in.Delim('{')
        if !in.Ok() {
            return in.Error()
        }
        for !in.IsDelim('}') {
`)
	if len(struct_.Fields) == 0 {
		// do not generate switch with only default

		qw422016.N().S(`            return `)
		qw422016.N().S(struct_.wr.gen.InternalPrefix())
		qw422016.N().S(`ErrorInvalidJSON(`)
		qw422016.N().Q(tlName)
		qw422016.N().S(`, "this object can't have properties")
`)
	} else {
		qw422016.N().S(`            key := in.UnsafeFieldName(true)
            in.WantColon()
            switch key {
`)
		for _, field := range struct_.Fields {
			if field.IsTL2Omitted() {
				continue
			}
			fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

			qw422016.N().S(`            case "`)
			qw422016.N().S(field.OriginalName())
			qw422016.N().S(`":
                if prop`)
			qw422016.N().S(field.goName)
			qw422016.N().S(`Presented {
                    return `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorInvalidJSONWithDuplicatingKeys(`)
			qw422016.N().Q(tlName)
			qw422016.N().S(`, `)
			qw422016.N().Q(field.OriginalName())
			qw422016.N().S(`)
                }
                prop`)
			qw422016.N().S(field.goName)
			qw422016.N().S(`Presented = true
`)
			if field.IsBit() {
				qw422016.N().S(`                if err := `)
				qw422016.N().S(struct_.wr.gen.InternalPrefix())
				qw422016.N().S(`Json2ReadBool(in, &trueType`)
				qw422016.N().S(field.goName)
				qw422016.N().S(`Value); err != nil {
                    return err
                }
`)
			} else if field.IsTypeDependsFromLocalFields() {
				qw422016.N().S(`                raw`)
				qw422016.N().S(field.goName)
				qw422016.N().S(` = in.Raw()
                if !in.Ok() {
                    return in.Error()
                }
`)
			} else {
				qw422016.N().S(`                `)
				qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
				qw422016.N().S(`                `)
				qw422016.N().S(field.t.TypeJSON2ReadingCode(bytesVersion, directImports, struct_.wr.ins, "in", fieldAccess, formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk))
				qw422016.N().S(`
`)
			}
			if field.MaskTL2Bit() != nil {
				if field.IsBit() {
					qw422016.N().S(`                    if trueType`)
					qw422016.N().S(field.goName)
					qw422016.N().S(`Value {
                        item.`)
					qw422016.N().S(field.TL2MaskForOP("|="))
					qw422016.N().S(`
                    }
`)
				} else {
					qw422016.N().S(`                    item.`)
					qw422016.N().S(field.TL2MaskForOP("|="))
					qw422016.N().S(`
`)
				}
			}
		}
		qw422016.N().S(`                default: return `)
		qw422016.N().S(struct_.wr.gen.InternalPrefix())
		qw422016.N().S(`ErrorInvalidJSONExcessElement(`)
		qw422016.N().Q(tlName)
		qw422016.N().S(`, key)
            }
            in.WantComma()
`)
	}
	qw422016.N().S(`        }
        in.Delim('}')
        if !in.Ok() {
            return in.Error()
        }
    }
`)
	// BLOCK: reset fully independent props (this is required to start tweaking field masks below), when they are absent

	for _, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		if field.IsBit() || len(field.NatArgs()) != 0 {
			continue
		}
		qw422016.N().S(`            if !prop`)
		qw422016.N().S(field.goName)
		qw422016.N().S(`Presented {
                    `)
		qw422016.N().S(field.TypeResettingCode(bytesVersion, directImports, struct_.wr.ins))
		qw422016.N().S(`
            }
`)
	}
	// BLOCK: set TL2 masks from TL1 masks, if not presented by user. This code disappears during TL1.5->TL2 switch
	// we do it before we start modifying TL1 masks in the subsequent block below, because otherwise setting any TL2 property
	// depending on the same TL1 mask will set them all, preventing setting them independently.
	// so TL1-serialized JSON will correctly set all TL2 masks, some manually constructed JSONs without explicit TL1 masks
	// will break and to fix them users will have to either set TL1 masks or set TL2 masks (encourage them to set TL2 masks)..

	for _, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		if field.FieldMask() == nil || field.MaskTL2Bit() == nil {
			continue
		}
		qw422016.N().S(`            if !prop`)
		qw422016.N().S(field.goName)
		qw422016.N().S(`Presented && `)
		qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
		qw422016.N().S(` & (1<<`)
		qw422016.E().V(field.BitNumber())
		qw422016.N().S(`) != 0 {
                item.`)
		qw422016.N().S(field.TL2MaskForOP("|="))
		qw422016.N().S(`
            }
`)
	}
	// BLOCK: set TL1 field masks recursively, if prop referencing them is present

	for _, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		if field.FieldMask() == nil {
			continue
		}
		qw422016.N().S(`        if `)
		if field.IsBit() {
			qw422016.N().S(`trueType`)
			qw422016.N().S(field.goName)
			qw422016.N().S(`Value`)
		} else {
			qw422016.N().S(`prop`)
			qw422016.N().S(field.goName)
			qw422016.N().S(`Presented`)
		}
		qw422016.N().S(` {
`)
		curField := field // this if can be empty in generated code, we are OK with this

		for curField.FieldMask() != nil {
			if !curField.FieldMask().IsField() {
				mask := fmt.Sprintf("%s", formatNatArg(struct_.Fields, *curField.FieldMask()))
				bit := int(curField.BitNumber())

				if !struct_.wr.HasTL2() {
					// we stop checking that TL1 masks are in sync, because they can differ for TL2 types

					qw422016.N().S(`                        if `)
					qw422016.N().S(mask)
					qw422016.N().S(` & (1 << `)
					qw422016.E().V(bit)
					qw422016.N().S(`) == 0 {
                            return `)
					qw422016.N().S(struct_.wr.gen.InternalPrefix())
					qw422016.N().S(`ErrorInvalidJSON(`)
					qw422016.N().Q(tlName)
					qw422016.N().S(`, "field '`)
					qw422016.N().S(field.OriginalName())
					qw422016.N().S(`' is set, but will be ignored, because corresponding fieldmask `)
					qw422016.N().S(mask)
					qw422016.N().S(` bit `)
					qw422016.E().V(bit)
					qw422016.N().S(` is 0")
                        }
`)
				}
				break
			}
			ancestor := struct_.Fields[curField.FieldMask().FieldIndex()]

			qw422016.N().S(`                item.`)
			qw422016.N().S(ancestor.goName)
			qw422016.N().S(` |= 1 << `)
			qw422016.E().V(curField.BitNumber())
			qw422016.N().S(`
`)
			curField = ancestor

		}
		qw422016.N().S(`        }
`)
	}
	// BLOCK: trueType with false values validation

	if !struct_.wr.HasTL2() {
		// we stop checking that TL1 masks are in sync, because they can differ for TL2 types

		for _, field := range struct_.Fields {
			if field.IsTL2Omitted() {
				continue
			}
			if !field.IsBit() {
				continue
			}
			mask := fmt.Sprintf("%s", formatNatArg(struct_.Fields, *field.FieldMask()))
			bit := int(field.BitNumber())

			qw422016.N().S(`            if prop`)
			qw422016.N().S(field.goName)
			qw422016.N().S(`Presented && !trueType`)
			qw422016.N().S(field.goName)
			qw422016.N().S(`Value && (`)
			qw422016.N().S(mask)
			qw422016.N().S(` & (1 << `)
			qw422016.E().V(bit)
			qw422016.N().S(`) != 0) {
                return `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorInvalidJSON(`)
			qw422016.N().Q(tlName)
			qw422016.N().S(`, "field '`)
			qw422016.N().S(field.OriginalName())
			qw422016.N().S(`' is explicitly set to false, but corresponding fieldmask `)
			qw422016.N().S(mask)
			qw422016.N().S(` bit `)
			qw422016.E().V(bit)
			qw422016.N().S(` is 1")
            }
`)
		}
	}
	// BLOCK: read presented IsTypeDependsFromLocalFields fields

	for _, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		if field.IsBit() || len(field.NatArgs()) == 0 || !field.IsTypeDependsFromLocalFields() {
			continue
		}
		fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

		qw422016.N().S(`        `)
		qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
		qw422016.N().S(`        if prop`)
		qw422016.N().S(field.goName)
		qw422016.N().S(`Presented {
            in`)
		qw422016.N().S(field.goName)
		qw422016.N().S(` := &basictl.JsonLexer{Data:raw`)
		qw422016.N().S(field.goName)
		qw422016.N().S(`}
            `)
		qw422016.N().S(field.t.TypeJSON2ReadingCode(bytesVersion, directImports, struct_.wr.ins, "in"+field.goName, fieldAccess, formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk))
		qw422016.N().S(`
        }
`)
	}
	// BLOCK: read/reset remaining fields, including those from previous block

	for _, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		if field.IsBit() || len(field.NatArgs()) == 0 {
			continue
		}
		qw422016.N().S(`            if !prop`)
		qw422016.N().S(field.goName)
		qw422016.N().S(`Presented {
`)
		if field.MaskTL2Bit() != nil {
			qw422016.N().S(`                    if item.`)
			qw422016.N().S(field.TL2MaskForOP("&"))
			qw422016.N().S(` != 0 {
`)
		} else if field.FieldMask() != nil {
			qw422016.N().S(`                    if `)
			qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
			qw422016.N().S(` & (1 << `)
			qw422016.E().V(field.BitNumber())
			qw422016.N().S(`) != 0 {
`)
		}
		fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

		qw422016.N().S(`                    `)
		qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
		qw422016.N().S(`                    `)
		qw422016.N().S(field.t.TypeJSON2ReadingCode(bytesVersion, directImports, struct_.wr.ins, "nil", fieldAccess, formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk))
		qw422016.N().S(`
`)
		if field.FieldMask() != nil || field.MaskTL2Bit() != nil {
			qw422016.N().S(`                    }
`)
		}
		qw422016.N().S(`            }
`)
	}
	qw422016.N().S(`    return nil
}

`)
}

func (struct_ *TypeRWStruct) writereadJSONCode(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamreadJSONCode(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) readJSONCode(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writereadJSONCode(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamreadJsonWithResetForRaw(qw422016 *qt422016.Writer, field Field, bytesVersion bool, directImports *DirectImports) {
	qw422016.N().S(`        in`)
	qw422016.N().S(field.goName)
	qw422016.N().S(` := basictl.JsonLexer{Data:raw`)
	qw422016.N().S(field.goName)
	qw422016.N().S(`}
`)
	fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

	qw422016.N().S(`        `)
	qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
	qw422016.N().S(`        `)
	qw422016.N().S(field.t.TypeJSON2ReadingCode(bytesVersion, directImports, struct_.wr.ins, "&in"+field.goName, fieldAccess, formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk))
	qw422016.N().S(`
`)
}

func (struct_ *TypeRWStruct) writereadJsonWithResetForRaw(qq422016 qtio422016.Writer, field Field, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamreadJsonWithResetForRaw(qw422016, field, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) readJsonWithResetForRaw(field Field, bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writereadJsonWithResetForRaw(qb422016, field, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamwriteJSONCode(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	goName := addBytes(struct_.wr.goGlobalName, bytesVersion)
	natArgsDecl := struct_.wr.formatNatArgsDecl()
	natArgsCall := struct_.wr.formatNatArgsDeclCall()
	writeNeedsError := struct_.wr.hasErrorInWriteMethods

	qw422016.N().S(`
// This method is general version of WriteJSON, use it instead!
func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte`)
	qw422016.N().S(natArgsDecl)
	qw422016.N().S(`) (_ []byte, err error) {
    return item.WriteJSONOpt(jctx, w`)
	qw422016.N().S(natArgsCall)
	qw422016.N().S(`)`)
	if !writeNeedsError {
		qw422016.N().S(`, nil`)
	}
	qw422016.N().S(`}

func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) WriteJSON(w []byte`)
	qw422016.N().S(natArgsDecl)
	qw422016.N().S(`) `)
	qw422016.N().S(wrapWithError(writeNeedsError, "[]byte"))
	qw422016.N().S(` {
    return item.WriteJSONOpt(nil, w`)
	qw422016.N().S(natArgsCall)
	qw422016.N().S(`)
}
func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte`)
	qw422016.N().S(natArgsDecl)
	qw422016.N().S(`) `)
	qw422016.N().S(wrapWithError(writeNeedsError, "[]byte"))
	qw422016.N().S(` {
    w = append(w, '{')
`)
	for _, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

		if field.IsBit() {
			if field.MaskTL2Bit() != nil {
				qw422016.N().S(`                if item.`)
				qw422016.N().S(field.TL2MaskForOP("&"))
				qw422016.N().S(` != 0 {
`)
			} else {
				qw422016.N().S(`                if `)
				qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
				qw422016.N().S(` & (1<<`)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`) != 0 {
`)
			}
			qw422016.N().S(`                    w = basictl.JSONAddCommaIfNeeded(w)
                    w = append(w, `)
			qw422016.N().S("`")
			qw422016.N().Q(field.OriginalName())
			qw422016.N().S(`:true`)
			qw422016.N().S("`")
			qw422016.N().S(`...)
                }
`)
			continue
		}
		if field.t.IsTrueType() {
			continue
		}
		emptyCond := field.t.TypeJSONEmptyCondition(bytesVersion, fieldAccess, fieldAsterisk)

		if field.MaskTL2Bit() != nil {
			qw422016.N().S(`            if item.`)
			qw422016.N().S(field.TL2MaskForOP("&"))
			qw422016.N().S(` != 0 {
`)
		} else if field.FieldMask() != nil {
			qw422016.N().S(`            if `)
			qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
			qw422016.N().S(` & (1<<`)
			qw422016.E().V(field.BitNumber())
			qw422016.N().S(`) != 0 {
`)
		} else if emptyCond != "" && struct_.wr.originateFromTL2 {
			qw422016.N().S(`            if `)
			qw422016.N().S(emptyCond)
			qw422016.N().S(` {
`)
		} else if emptyCond != "" && !struct_.wr.originateFromTL2 {
			qw422016.N().S(`            backupIndex`)
			qw422016.N().S(field.goName)
			qw422016.N().S(` := len(w)
`)
		}
		qw422016.N().S(`                w = basictl.JSONAddCommaIfNeeded(w)
                w = append(w, `)
		qw422016.N().S("`")
		qw422016.N().S(`"`)
		qw422016.E().S(field.OriginalName())
		qw422016.N().S(`":`)
		qw422016.N().S("`")
		qw422016.N().S(`...)
                `)
		qw422016.N().S(field.t.TypeJSONWritingCode(bytesVersion, directImports, struct_.wr.ins, fieldAccess, formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk, field.t.hasErrorInWriteMethods))
		qw422016.N().S(`
`)
		if field.MaskTL2Bit() != nil {
			qw422016.N().S(`            }
`)
		} else if field.FieldMask() != nil {
			qw422016.N().S(`            }
`)
		} else if emptyCond != "" && struct_.wr.originateFromTL2 {
			qw422016.N().S(`            }
`)
		} else if emptyCond != "" && !struct_.wr.originateFromTL2 {
			qw422016.N().S(`            if !(`)
			qw422016.N().S(emptyCond)
			qw422016.N().S(`) {
                    w = w[:backupIndex`)
			qw422016.N().S(field.goName)
			qw422016.N().S(`]
            }
`)
		}
	}
	qw422016.N().S(`    return append(w, '}')`)
	if writeNeedsError {
		qw422016.N().S(`, nil`)
	}
	qw422016.N().S(`}
`)
}

func (struct_ *TypeRWStruct) writewriteJSONCode(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamwriteJSONCode(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) writeJSONCode(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writewriteJSONCode(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamfunctionCode(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	if struct_.ResultType == nil {
		return
	}
	goName := addBytes(struct_.wr.goGlobalName, bytesVersion)
	retArg := struct_.ResultType.TypeString2(bytesVersion, directImports, struct_.wr.ins, false, false)

	if struct_.wr.gen.options.Go.GenerateLegacyReadWrite {
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadResult(w []byte, ret *`)
		qw422016.N().S(retArg)
		qw422016.N().S(`) (_ []byte, err error) {
    return item.ReadResultTL1(w, ret)
}
`)
	}
	qw422016.N().S(`func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) ReadResultTL1(w []byte, ret *`)
	qw422016.N().S(retArg)
	qw422016.N().S(`) (_ []byte, err error) {
`)
	if struct_.wr.originateFromTL2 {
		qw422016.N().S(`        return w, basictl.TL2Error("not implemented for tl2 type")
`)
	} else {
		if struct_.resultHasFetcher() {
			qw422016.N().S(`            var fetcher any
`)
		}
		qw422016.N().S(`        `)
		qw422016.N().S(struct_.ResultType.TypeReadingCode(bytesVersion, directImports, struct_.wr.ins, "ret", false, formatNatArgs(struct_.Fields, struct_.ResultNatArgs), true, true))
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`}

`)
	if struct_.wr.gen.options.Go.GenerateLegacyReadWrite {
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) WriteResult(w []byte, ret `)
		qw422016.N().S(retArg)
		qw422016.N().S(`) (_ []byte, err error) {
    return item.WriteResultTL1(w, ret)
}
`)
	}
	qw422016.N().S(`func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) WriteResultTL1(w []byte, ret `)
	qw422016.N().S(retArg)
	qw422016.N().S(`) (_ []byte, err error) {
`)
	if struct_.wr.originateFromTL2 {
		qw422016.N().S(`        return w, basictl.TL2Error("not implemented for tl2 type")
`)
	} else {
		if struct_.resultHasFetcher() {
			qw422016.N().S(`            var fetcher any
`)
		}
		qw422016.N().S(`        `)
		qw422016.N().S(struct_.ResultType.TypeWritingCode(bytesVersion, directImports, struct_.wr.ins, "ret", false, formatNatArgs(struct_.Fields, struct_.ResultNatArgs), false, false, struct_.ResultType.hasErrorInWriteMethods))
		qw422016.N().S(`
        return w, nil
`)
	}
	qw422016.N().S(`}

`)
	if struct_.wr.HasTL2() {
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadResultTL2(r []byte, tctx *basictl.TL2ReadContext, ret *`)
		qw422016.N().S(retArg)
		qw422016.N().S(`) (_ []byte, err error) {
`)
		if struct_.pureTypeStruct.IsResultAlias() {
			qw422016.N().S(`    return ret.ReadTL2(r, tctx)
`)
		} else {
			qw422016.N().S(`    currentSize := 0
    if r, currentSize, err = basictl.TL2ParseSize(r); err != nil { return r, err }
    if currentSize == 0 {
        `)
			qw422016.N().S(struct_.ResultType.TypeResettingCode(bytesVersion, directImports, struct_.wr.ins, "ret", true))
			qw422016.N().S(`
        return r, nil
    }
    if len(r) < currentSize {
        return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
    }

    currentR := r[:currentSize]
    r = r[currentSize:]

    var block byte
    if currentR, err = basictl.ByteRead(currentR, &block); err != nil { return r, err }
    if block & 1 != 0 {
        var index int
        if currentR, index, err = basictl.TL2ParseSize(currentR); err != nil { return r, err }
        if index != 0 {
            return currentR, basictl.TL2Error("function result must not use variant type field")
        }
    }

    if block & 2 != 0 {
        `)
			qw422016.N().S(struct_.ResultType.ReadTL2Call(directImports, bytesVersion, "currentR", "ret", true, struct_.wr.ins, true))
			qw422016.N().S(`
    } else {
        `)
			qw422016.N().S(struct_.ResultType.TypeResettingCode(bytesVersion, directImports, struct_.wr.ins, "ret", true))
			qw422016.N().S(`
    }
    return r, nil
`)
		}
		qw422016.N().S(`}

`)
		if !struct_.pureTypeStruct.IsResultAlias() {
			qw422016.N().S(`func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) calculateLayoutResult(sizes []int, optimizeEmpty bool, ret `)
			qw422016.N().S(retArg)
			qw422016.N().S(`) ([]int, int) {
    sizes = append(sizes, `)
			qw422016.N().V(someHash(goName))
			qw422016.N().S(`)
    sizePosition := len(sizes)
    sizes = append(sizes, 0)

    currentSize := 1
    lastUsedByte := 0
    var sz int
    `)
			qw422016.N().S(struct_.ResultType.CalculateLayoutCall(directImports, bytesVersion, "sizes", "ret", true, struct_.wr.ins, false))
			qw422016.N().S(`
        lastUsedByte = currentSize
    }
    if lastUsedByte < currentSize {
        currentSize = lastUsedByte
    }
    sizes[sizePosition] = currentSize
    if currentSize == 0 {
        sizes = sizes[:sizePosition+1]
    }
    if !optimizeEmpty || currentSize != 0 {
        currentSize += basictl.TL2CalculateSize(currentSize)
    }
    `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`Unused(sz)
    return sizes, currentSize
}

func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) writeResultTL2(w []byte, sizes []int, optimizeEmpty bool, ret `)
			qw422016.N().S(retArg)
			qw422016.N().S(`) ([]byte, []int, int) {
    if sizes[0] != `)
			qw422016.N().V(someHash(goName))
			qw422016.N().S(` {
        panic("tl2: tag mismatch between calculate and write")
    }
    currentSize := sizes[1]
    sizes = sizes[2:]

    if optimizeEmpty && currentSize == 0 {`)
			// CalculateLayout was called with optimizeEmpty and object turned out empty

			qw422016.N().S(`return w, sizes, 0
    }
    w = basictl.TL2WriteSize(w, currentSize)
    if currentSize == 0 {
        return w, sizes, 1
    }
    oldLen := len(w)
    var sz int
    var currentBlock byte
    currentBlockPosition := len(w)
    w = append(w, 0)

    `)
			qw422016.N().S(struct_.ResultType.WriteTL2Call(directImports, bytesVersion, "sizes", "w", "ret", true, struct_.wr.ins, false))
			qw422016.N().S(`
        currentBlock |= 2
    }
    if currentBlockPosition < len(w) {
        w[currentBlockPosition] = currentBlock
    }
    if len(w) - oldLen != currentSize {
        panic("tl2: mismatch between calculate and write")
    }
    `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`Unused(sz)
    return w, sizes, currentSize
}
`)
		}
		qw422016.N().S(`
func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) WriteResultTL2(w []byte, tctx *basictl.TL2WriteContext, ret `)
		qw422016.N().S(retArg)
		qw422016.N().S(`) []byte {
`)
		if struct_.pureTypeStruct.IsResultAlias() {
			qw422016.N().S(`    return ret.WriteTL2(w, tctx)
`)
		} else {
			qw422016.N().S(`    var sizes, sizes2 []int
    if tctx != nil {
        sizes = tctx.SizeBuffer[:0]
    }
    sizes, _ = item.calculateLayoutResult(sizes, false, ret)
    w, sizes2, _ = item.writeResultTL2(w, sizes, false, ret)
    if len(sizes2) != 0 {
        panic("tl2: internal write did not consume all size data")
    }
    if tctx != nil {
        tctx.SizeBuffer = sizes
    }
    return w
`)
		}
		qw422016.N().S(`}

`)
	}
	qw422016.N().S(`
func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *`)
	qw422016.N().S(retArg)
	qw422016.N().S(`) error {
`)
	if struct_.ResultType.TypeJSON2ReadingRequiresContext() {
		qw422016.N().S(`    jctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
`)
	}
	qw422016.N().S(`    `)
	qw422016.N().S(struct_.ResultType.TypeJSON2ReadingCode(bytesVersion, directImports, struct_.wr.ins, "in", "ret", formatNatArgs(struct_.Fields, struct_.ResultNatArgs), true))
	qw422016.N().S(`
    return nil
}

func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) WriteResultJSON(w []byte, ret `)
	qw422016.N().S(retArg)
	qw422016.N().S(`) (_ []byte, err error) {
    return item.writeResultJSON(nil, w, ret)
}

func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) writeResultJSON(jctx *basictl.JSONWriteContext, w []byte, ret `)
	qw422016.N().S(retArg)
	qw422016.N().S(`) (_ []byte, err error) {
    `)
	qw422016.N().S(struct_.ResultType.TypeJSONWritingCode(bytesVersion, directImports, struct_.wr.ins, "ret", formatNatArgs(struct_.Fields, struct_.ResultNatArgs), false, struct_.ResultType.hasErrorInWriteMethods))
	qw422016.N().S(`
    return w, nil
}
`)
	if struct_.wr.gen.options.GenerateRandomCode {
		qw422016.N().S(`
func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
    var ret `)
		qw422016.N().S(retArg)
		qw422016.N().S(`
    `)
		qw422016.N().S(struct_.ResultType.TypeRandomCode(bytesVersion, directImports, struct_.wr.ins, "ret", formatNatArgs(struct_.Fields, struct_.ResultNatArgs), false))
		qw422016.N().S(`
    return item.WriteResultTL1(w, ret)
}
`)
	}
	qw422016.N().S(`
func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) ReadResultTL1WriteResultJSON(jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
  var ret `)
	qw422016.N().S(retArg)
	qw422016.N().S(`
  if r, err = item.ReadResultTL1(r, &ret); err != nil {
    return r, w, err
  }
  w, err = item.writeResultJSON(jctx, w, ret)
  return r, w, err
}

func (item *`)
	qw422016.N().S(goName)
	qw422016.N().S(`) ReadResultJSONWriteResultTL1(r []byte, w []byte) (_ []byte, _ []byte, err error) {
  var ret `)
	qw422016.N().S(retArg)
	qw422016.N().S(`
  if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
    return r, w, err
  }
  w, err = item.WriteResultTL1(w, ret)
  return r, w, err
}

`)
	if struct_.wr.gen.options.GenerateTL2() {
		qw422016.N().S(`func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
`)
		if !struct_.wr.HasTL2() {
			qw422016.N().S(`  return r, w, `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorTL2SerializersNotGenerated(`)
			qw422016.N().Q(struct_.wr.tlName.String())
			qw422016.N().S(`)
`)
		} else {
			qw422016.N().S(`  var ret `)
			qw422016.N().S(retArg)
			qw422016.N().S(`
  if r, err = item.ReadResultTL1(r, &ret); err != nil {
    return r, w, err
  }
  return r, item.WriteResultTL2(w, tctx, ret), nil
`)
		}
		qw422016.N().S(`}

func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
`)
		if !struct_.wr.HasTL2() {
			qw422016.N().S(`  return r, w, `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorTL2SerializersNotGenerated(`)
			qw422016.N().Q(struct_.wr.tlName.String())
			qw422016.N().S(`)
`)
		} else {
			qw422016.N().S(`  var ret `)
			qw422016.N().S(retArg)
			qw422016.N().S(`
  if r, err = item.ReadResultTL2(r, tctx, &ret); err != nil {
    return r, w, err
  }
  w, err = item.WriteResultTL1(w, ret)
  return r, w, err
`)
		}
		qw422016.N().S(`}

func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
`)
		if !struct_.wr.HasTL2() {
			qw422016.N().S(`  return r, w, `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorTL2SerializersNotGenerated(`)
			qw422016.N().Q(struct_.wr.tlName.String())
			qw422016.N().S(`)
`)
		} else {
			qw422016.N().S(`  var ret `)
			qw422016.N().S(retArg)
			qw422016.N().S(`
  if r, err = item.ReadResultTL2(r, tctx, &ret); err != nil {
    return r, w, err
  }
  w, err = item.writeResultJSON(jctx, w, ret)
  return r, w, err
`)
		}
		qw422016.N().S(`}

func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadResultJSONWriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
`)
		if !struct_.wr.HasTL2() {
			qw422016.N().S(`  return r, w, `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorTL2SerializersNotGenerated(`)
			qw422016.N().Q(struct_.wr.tlName.String())
			qw422016.N().S(`)
`)
		} else {
			qw422016.N().S(`  var ret `)
			qw422016.N().S(retArg)
			qw422016.N().S(`
  if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
    return r, w, err
  }
  return r, item.WriteResultTL2(w, tctx, ret), nil
`)
		}
		qw422016.N().S(`}
`)
	}
	for fieldId, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		fieldProps := struct_.pureTypeStruct.GetNatFieldUsage(fieldId, false, true)

		for _, bit := range fieldProps.UsedBits() {
			bitUsage := fieldProps.AffectedFields[bit]
			affectedTypes := make([]*TypeRWStruct, 0)
			for ins := range bitUsage {
				affectedType := struct_.wr.gen.getTypeMust(ins).trw.(*TypeRWStruct)

				affectedTypes = append(affectedTypes, affectedType)
			}
			sort.Slice(affectedTypes, func(i, j int) bool {
				return TypeRWWrapperLessGlobal(affectedTypes[i].wr, affectedTypes[j].wr) > 0
			})

			for _, affectedType := range affectedTypes {
				affectedFieldsByBit := bitUsage[affectedType.pureTypeStruct]
				affectedFieldsByBit = utils.SetToSlice(utils.SliceToSet(affectedFieldsByBit))
				sort.Slice(affectedFieldsByBit, func(i, j int) bool {
					return affectedFieldsByBit[i] < affectedFieldsByBit[j]
				})
				fieldNames := make([]string, len(affectedFieldsByBit))
				fieldNamesForComment := make([]string, len(affectedFieldsByBit))

				for i := range fieldNames {
					fieldNames[i] = affectedType.Fields[affectedFieldsByBit[i]].goName
					fieldNamesForComment[i] = "\"" + affectedType.Fields[affectedFieldsByBit[i]].OriginalName() + "\""
				}

				mergedFields := strings.Join(fieldNames, "And")
				mergedFieldsForComment := strings.Join(fieldNamesForComment, ", ")
				maybeS := ""
				if len(affectedFieldsByBit) > 1 {
					maybeS = "s"
				}

				qw422016.N().S(`// Set field`)
				qw422016.N().S(maybeS)
				qw422016.N().S(` `)
				qw422016.N().S(mergedFieldsForComment)
				qw422016.N().S(` in "`)
				qw422016.N().S(affectedType.wr.tlName.String())
				qw422016.N().S(`" by changing fieldMask "`)
				qw422016.N().S(field.OriginalName())
				qw422016.N().S(`"
func (item *`)
				qw422016.N().S(goName)
				qw422016.N().S(`) Set`)
				qw422016.N().S(affectedType.wr.goGlobalName)
				qw422016.N().S(mergedFields)
				qw422016.N().S(`(value bool) {
    if value {
        item.`)
				qw422016.N().S(field.goName)
				qw422016.N().S(` |= 1 << `)
				qw422016.N().D(int(bit))
				qw422016.N().S(`
    } else {
        item.`)
				qw422016.N().S(field.goName)
				qw422016.N().S(` &^= 1 << `)
				qw422016.N().D(int(bit))
				qw422016.N().S(`
    }
}

`)
			}
		}
	}
	qw422016.N().S(`
`)
}

func (struct_ *TypeRWStruct) writefunctionCode(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamfunctionCode(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) functionCode(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writefunctionCode(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamresetFields(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	for _, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		if field.t.IsTrueType() || field.IsBit() {
			continue
		}
		qw422016.N().S(`        `)
		qw422016.N().S(field.TypeResettingCode(bytesVersion, directImports, struct_.wr.ins))
		qw422016.N().S(`
`)
	}
	for _, tl2mask := range struct_.AllNewTL2Masks() {
		qw422016.N().S(`         item.`)
		qw422016.N().S(tl2mask)
		qw422016.N().S(` = 0
`)
	}
}

func (struct_ *TypeRWStruct) writeresetFields(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamresetFields(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) resetFields(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writeresetFields(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamrandomFields(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	for _, tl2mask := range struct_.AllNewTL2Masks() {
		qw422016.N().S(`         item.`)
		qw422016.N().S(tl2mask)
		qw422016.N().S(` = 0
`)
	}
	if struct_.wr.originateFromTL2 {
		for _, field := range struct_.Fields {
			if field.IsTL2Omitted() {
				continue
			}
			fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

			if field.recursive {
				qw422016.N().S(`                  rg.IncreaseDepth()
`)
			}
			if field.MaskTL2Bit() != nil {
				qw422016.N().S(`                if basictl.RandomInt(rg) & 1 != 0 {
                    item.`)
				qw422016.N().S(field.TL2MaskForOP("|="))
				qw422016.N().S(`
`)
				if !field.IsBit() {
					qw422016.N().S(`                            `)
					qw422016.N().S(field.t.TypeRandomCode(bytesVersion, directImports, struct_.wr.ins, fieldAccess, formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk))
					qw422016.N().S(`
                        }else{
                            `)
					qw422016.N().S(field.TypeResettingCode(bytesVersion, directImports, struct_.wr.ins))
					qw422016.N().S(`
`)
				}
				qw422016.N().S(`                }
`)
			} else {
				qw422016.N().S(`                    `)
				qw422016.N().S(field.t.TypeRandomCode(bytesVersion, directImports, struct_.wr.ins, fieldAccess, formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk))
				qw422016.N().S(`
`)
			}
			if field.recursive {
				qw422016.N().S(`                  rg.DecreaseDepth()
`)
			}
		}
		return
	}
	for fieldId, field := range struct_.Fields {
		if field.IsTL2Omitted() {
			continue
		}
		fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

		if field.IsBit() {
			if field.MaskTL2Bit() != nil {
				qw422016.N().S(`                if `)
				qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
				qw422016.N().S(` & (1<<`)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`) != 0 {
                     item.`)
				qw422016.N().S(field.TL2MaskForOP("|="))
				qw422016.N().S(`
                }
`)
			}
			continue
		}
		if field.FieldMask() != nil {
			qw422016.N().S(`if `)
			qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
			qw422016.N().S(` & (1<<`)
			qw422016.E().V(field.BitNumber())
			qw422016.N().S(`) != 0 {
`)
			if field.MaskTL2Bit() != nil {
				qw422016.N().S(`            item.`)
				qw422016.N().S(field.TL2MaskForOP("|="))
				qw422016.N().S(`
`)
			}
		}
		if field.recursive {
			qw422016.N().S(`rg.IncreaseDepth()
`)
		}
		qw422016.N().S(`        `)
		qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
		if fieldProps := struct_.pureTypeStruct.GetNatFieldUsage(fieldId, true, true); fieldProps.UsedAsMask || fieldProps.UsedAsSize {
			if fieldProps.UsedAsMask {
				bitMask := uint32(0)
				for _, indexPosition := range fieldProps.UsedBits() {
					bitMask |= 1 << indexPosition
				}

				qw422016.N().S(`item.`)
				qw422016.N().S(field.goName)
				qw422016.N().S(`= basictl.RandomFieldMask(rg, `)
				qw422016.E().S(fmt.Sprintf("0b%b", bitMask))
				qw422016.N().S(`)
`)
				if fieldProps.UsedAsSize {
					qw422016.N().S(`item.`)
					qw422016.N().S(field.goName)
					qw422016.N().S(` = rg.LimitValue(item.`)
					qw422016.N().S(field.goName)
					qw422016.N().S(`)
`)
				}
			} else {
				qw422016.N().S(`item.`)
				qw422016.N().S(field.goName)
				qw422016.N().S(` = basictl.RandomSize(rg)
`)
			}
		} else {
			qw422016.N().S(field.t.TypeRandomCode(bytesVersion, directImports, struct_.wr.ins, fieldAccess, formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk))
			qw422016.N().S(`
`)
		}
		if field.recursive {
			qw422016.N().S(`rg.DecreaseDepth()
`)
		}
		if field.FieldMask() != nil {
			qw422016.N().S(`} else {
    `)
			qw422016.N().S(field.TypeResettingCode(bytesVersion, directImports, struct_.wr.ins))
			qw422016.N().S(`
}
`)
		}
	}
}

func (struct_ *TypeRWStruct) writerandomFields(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamrandomFields(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) randomFields(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writerandomFields(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamwriteFields(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	if struct_.wr.originateFromTL2 {
		if struct_.wr.hasErrorInWriteMethods {
			qw422016.N().S(`    return w, basictl.TL2Error("not implemented for tl2 type")
`)
		} else {
			qw422016.N().S(`    panic(basictl.TL2Error("not implemented for tl2 type"))
`)
		}
		return
	}
	for _, field := range struct_.Fields {
		if field.IsBit() {
			if !field.Bare() {
				// special case for TL1

				qw422016.N().S(`                if `)
				qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
				qw422016.N().S(` & (1<<`)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`) != 0 {
                    `)
				qw422016.N().S(fmt.Sprintf("w = basictl.NatWrite(w, 0x%08x)", field.t.tlTag))
				qw422016.N().S(`
                }
`)
			}
			continue
		}
		fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

		writingCode := field.t.TypeWritingCode(bytesVersion, directImports, struct_.wr.ins, fieldAccess, field.Bare(), formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk, false, field.t.hasErrorInWriteMethods)

		if field.FieldMask() != nil {
			qw422016.N().S(`        if `)
			qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
			qw422016.N().S(` & (1<<`)
			qw422016.E().V(field.BitNumber())
			qw422016.N().S(`) != 0 {
`)
		}
		if field.recursive {
			// non-optional recursive field (h next:Maybe<h> = H) because we do not want 2 versions of Maybe

			qw422016.N().S(`        if `)
			qw422016.N().S(fieldAccess)
			qw422016.N().S(` == nil {
            var tmpValue `)
			qw422016.N().S(field.t.TypeString2(bytesVersion, directImports, struct_.wr.ins, false, false))
			qw422016.N().S(`
            `)
			qw422016.N().S(field.t.TypeWritingCode(bytesVersion, directImports, struct_.wr.ins, "tmpValue", field.Bare(), formatNatArgs(struct_.Fields, field.NatArgs()), false, false, field.t.hasErrorInWriteMethods))
			qw422016.N().S(`
        } else {
            `)
			qw422016.N().S(writingCode)
			qw422016.N().S(`
        }
`)
		} else {
			qw422016.N().S(`        `)
			qw422016.N().S(writingCode)
			qw422016.N().S(`
`)
		}
		if field.FieldMask() != nil {
			qw422016.N().S(`        }
`)
		}
	}
	if struct_.wr.hasErrorInWriteMethods {
		qw422016.N().S(`return w, nil
`)
	} else {
		qw422016.N().S(`return w
`)
	}
}

func (struct_ *TypeRWStruct) writewriteFields(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamwriteFields(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) writeFields(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writewriteFields(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamreadFields(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	if struct_.wr.originateFromTL2 {
		qw422016.N().S(`    return w, basictl.TL2Error("not implemented for tl2 type")
`)
		return
	}
	for _, tl2mask := range struct_.AllNewTL2Masks() {
		qw422016.N().S(`         item.`)
		qw422016.N().S(tl2mask)
		qw422016.N().S(` = 0
`)
	}
	lastWritten := false

	for i, field := range struct_.Fields {
		last := i == len(struct_.Fields)-1 && field.FieldMask() == nil
		lastWritten = lastWritten || last

		if field.IsBit() {
			if field.MaskTL2Bit() != nil {
				qw422016.N().S(`                if `)
				qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
				qw422016.N().S(` & (1<<`)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`) != 0 {
                    item.`)
				qw422016.N().S(field.TL2MaskForOP("|="))
				qw422016.N().S(`
                }
`)
			}
			if !field.Bare() {
				// special rare case for TL1, let optimizer combine 2 expressions

				qw422016.N().S(`                if `)
				qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
				qw422016.N().S(` & (1<<`)
				qw422016.E().V(field.BitNumber())
				qw422016.N().S(`) != 0 {
                    `)
				qw422016.N().S(wrapLastW(last, fmt.Sprintf("basictl.NatReadExactTag(w, 0x%08x)", field.t.tlTag), true))
				qw422016.N().S(`
                }
`)
			}
			continue
		}
		fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

		if field.FieldMask() != nil {
			qw422016.N().S(`if `)
			qw422016.N().S(formatNatArg(struct_.Fields, *field.FieldMask()))
			qw422016.N().S(` & (1<<`)
			qw422016.E().V(field.BitNumber())
			qw422016.N().S(`) != 0 {
`)
			if field.MaskTL2Bit() != nil {
				qw422016.N().S(`            item.`)
				qw422016.N().S(field.TL2MaskForOP("|="))
				qw422016.N().S(`
`)
			}
		}
		qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
		qw422016.N().S(field.t.TypeReadingCode(bytesVersion, directImports, struct_.wr.ins, fieldAccess, field.Bare(), formatNatArgs(struct_.Fields, field.NatArgs()), fieldAsterisk, last))
		qw422016.N().S(`
`)
		if field.FieldMask() != nil {
			qw422016.N().S(`} else {
        `)
			qw422016.N().S(field.TypeResettingCode(bytesVersion, directImports, struct_.wr.ins))
			qw422016.N().S(`
}
`)
		}
	}
	if !lastWritten {
		qw422016.N().S(`return w, nil`)
	}
	// keeps all function body on the same line

}

func (struct_ *TypeRWStruct) writereadFields(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamreadFields(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) readFields(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writereadFields(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (struct_ *TypeRWStruct) streamgenerateTL2Code(qw422016 *qt422016.Writer, bytesVersion bool, directImports *DirectImports) {
	goName := addBytes(struct_.wr.goGlobalName, bytesVersion)
	tlName := struct_.wr.tlName.String()

	if struct_.isAlias() {
		field := struct_.Fields[0]

		qw422016.N().S(`
func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
`)
		if !struct_.wr.HasTL2() {
			qw422016.N().S(`    panic(`)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorTL2SerializersNotGenerated(`)
			qw422016.N().Q(tlName)
			qw422016.N().S(`))
`)
		} else {
			qw422016.N().S(`    var sizes []int
    if tctx != nil {
        sizes = tctx.SizeBuffer[:0]
    }
    var sz int
    var currentSize int
    `)
			qw422016.N().S(field.t.CalculateLayoutCall(directImports, bytesVersion, "sizes", "item.ptr()", false, struct_.wr.ins, true))
			qw422016.N().S(`
    `)
			qw422016.N().S(field.t.WriteTL2Call(directImports, bytesVersion, "sizes", "w", "item.ptr()", false, struct_.wr.ins, true))
			qw422016.N().S(`

    `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`Unused(currentSize)
    `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`Unused(sz)
    if tctx != nil {
        tctx.SizeBuffer = sizes
    }
    return w
`)
		}
		qw422016.N().S(`}

func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) InternalReadTL2(r []byte) (_ []byte, err error) {
`)
		if !struct_.wr.HasTL2() {
			qw422016.N().S(`    return r, `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorTL2SerializersNotGenerated(`)
			qw422016.N().Q(tlName)
			qw422016.N().S(`)
`)
		} else {
			qw422016.N().S(`    `)
			qw422016.N().S(field.t.ReadTL2Call(directImports, bytesVersion, "r", "item.ptr()", false, struct_.wr.ins, true))
			qw422016.N().S(`
    return r, nil
`)
		}
		qw422016.N().S(`}

func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
    return item.InternalReadTL2(r)
}
`)
	} else {
		qw422016.N().S(`
`)
		if struct_.wr.HasTL2() {
			qw422016.N().S(`func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) CalculateLayout(sizes []int, optimizeEmpty bool) ([]int, int) {
`)
			if len(struct_.Fields) == 0 && (struct_.unionParent == nil || struct_.unionIndex == 0) {
				qw422016.N().S(`        if optimizeEmpty {
            return sizes, 0
        }
        return sizes, 1
`)
			} else {
				qw422016.N().S(`    sizes = append(sizes, `)
				qw422016.N().V(someHash(goName))
				qw422016.N().S(`)
    sizePosition := len(sizes)
    sizes = append(sizes, 0)

    currentSize := 1
    lastUsedByte := 0
    var sz int

`)
				if struct_.unionParent != nil && struct_.unionIndex != 0 {
					qw422016.N().S(`        // add constructor No for union type in case of non first option
        currentSize += basictl.TL2CalculateSize(`)
					qw422016.N().D(struct_.unionIndex)
					qw422016.N().S(`)
        lastUsedByte = currentSize
`)
				}
				for fieldIndex, field := range struct_.Fields {
					if (fieldIndex+1)%8 == 0 {
						qw422016.N().S(`            currentSize++
`)
					}
					if field.IsTL2Omitted() {
						continue
					}
					fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

					if field.MaskTL2Bit() != nil {
						qw422016.N().S(`            if item.`)
						qw422016.N().S(field.TL2MaskForOP("&"))
						qw422016.N().S(` != 0 {
`)
						if !field.IsBit() {
							qw422016.N().S(`                    `)
							qw422016.N().S(field.t.CalculateLayoutCall(directImports, bytesVersion, "sizes", fieldAccess, false, struct_.wr.ins, fieldAsterisk))
							qw422016.N().S(`
`)
						}
					} else {
						// we modify struct when writing non-optional recursive field (h next:Maybe<h> = H) because we do not want 2 versions of Maybe

						qw422016.N().S(`            `)
						qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
						qw422016.N().S(`            `)
						qw422016.N().S(field.t.CalculateLayoutCall(directImports, bytesVersion, "sizes", fieldAccess, true, struct_.wr.ins, fieldAsterisk))
						qw422016.N().S(`
`)
					}
					qw422016.N().S(`            lastUsedByte = currentSize
        }
`)
				}
				qw422016.N().S(`
    if lastUsedByte < currentSize {
        currentSize = lastUsedByte
    }
    sizes[sizePosition] = currentSize
    if currentSize == 0 {
        sizes = sizes[:sizePosition+1]
    }
    if !optimizeEmpty || currentSize != 0 {
        currentSize += basictl.TL2CalculateSize(currentSize)
    }
    `)
				qw422016.N().S(struct_.wr.gen.InternalPrefix())
				qw422016.N().S(`Unused(sz)
    return sizes, currentSize
`)
			}
			qw422016.N().S(`}

func (item *`)
			qw422016.N().S(goName)
			qw422016.N().S(`) InternalWriteTL2(w []byte, sizes []int, optimizeEmpty bool) ([]byte, []int, int) {
`)
			if len(struct_.Fields) == 0 && (struct_.unionParent == nil || struct_.unionIndex == 0) {
				qw422016.N().S(`        if optimizeEmpty {
            return w, sizes, 0
        }
        w = append(w, 0)
        return w, sizes, 1
`)
			} else {
				qw422016.N().S(`    if sizes[0] != `)
				qw422016.N().V(someHash(goName))
				qw422016.N().S(` {
        panic("tl2: tag mismatch between calculate and write")
    }
    currentSize := sizes[1]
    sizes = sizes[2:]
    if optimizeEmpty && currentSize == 0 {`)
				// CalculateLayout was called with optimizeEmpty and object turned out empty

				qw422016.N().S(`        return w, sizes, 0
    }
    w = basictl.TL2WriteSize(w, currentSize)
    if currentSize == 0 {
        return w, sizes, 1
    }
    oldLen := len(w)
    var sz int
    var currentBlock byte
    currentBlockPosition := len(w)
    w = append(w, 0)
`)
				if struct_.unionParent != nil && struct_.unionIndex != 0 {
					// add constructor No for union type in case of non first option

					qw422016.N().S(`        w = basictl.TL2WriteSize(w, `)
					qw422016.N().D(struct_.unionIndex)
					qw422016.N().S(`)
        currentBlock |= 1
`)
				}
				for fieldIndex, field := range struct_.Fields {
					if (fieldIndex+1)%8 == 0 {
						qw422016.N().S(`            if currentBlockPosition < len(w) {
                w[currentBlockPosition] = currentBlock
            }
            currentBlock = 0
`)
						// we cannot return here, because fields must pop from sizes, so we will call WriteTL2.
						// this optimization starts only for field 7 and further, so it is actually rare
						// start the next block

						qw422016.N().S(`            currentBlockPosition = len(w)
            if len(w) - oldLen < currentSize {
                w = append(w, 0)
            }
`)
					}
					if field.IsTL2Omitted() {
						continue
					}
					fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

					if field.MaskTL2Bit() != nil {
						qw422016.N().S(`            if item.`)
						qw422016.N().S(field.TL2MaskForOP("&"))
						qw422016.N().S(` != 0 {
`)
						if !field.IsBit() {
							qw422016.N().S(`                    `)
							qw422016.N().S(field.t.WriteTL2Call(directImports, bytesVersion, "sizes", "w", fieldAccess, false, struct_.wr.ins, fieldAsterisk))
							qw422016.N().S(`
`)
						}
					} else {
						// we modify struct when writing non-optional recursive field (h next:Maybe<h> = H) because we do not want 2 versions of Maybe

						qw422016.N().S(`            `)
						qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
						qw422016.N().S(`            `)
						qw422016.N().S(field.t.WriteTL2Call(directImports, bytesVersion, "sizes", "w", fieldAccess, true, struct_.wr.ins, fieldAsterisk))
						qw422016.N().S(`
`)
					}
					qw422016.N().S(`            currentBlock |= `)
					qw422016.E().V(1 << ((fieldIndex + 1) % 8))
					qw422016.N().S(`
        }
`)
				}
				qw422016.N().S(`    if currentBlockPosition < len(w) {
        w[currentBlockPosition] = currentBlock
    }
    if len(w) - oldLen != currentSize {
        panic("tl2: mismatch between calculate and write")
    }
    `)
				qw422016.N().S(struct_.wr.gen.InternalPrefix())
				qw422016.N().S(`Unused(sz)
    return w, sizes, 1
`)
			}
			qw422016.N().S(`}
`)
		}
		qw422016.N().S(`
func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
`)
		if !struct_.wr.HasTL2() {
			qw422016.N().S(`        panic(`)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorTL2SerializersNotGenerated(`)
			qw422016.N().Q(tlName)
			qw422016.N().S(`))
`)
		} else {
			qw422016.N().S(`    var sizes, sizes2 []int
    if tctx != nil {
        sizes = tctx.SizeBuffer[:0]
    }
    sizes, _ = item.CalculateLayout(sizes, false)
    w, sizes2, _ = item.InternalWriteTL2(w, sizes, false)
    if len(sizes2) != 0 {
        panic("tl2: internal write did not consume all size data")
    }
    if tctx != nil {
        tctx.SizeBuffer = sizes
    }
    return w
`)
		}
		qw422016.N().S(`}

`)
		if struct_.wr.HasTL2() {
			if struct_.unionParent == nil {
				qw422016.N().S(`func (item *`)
				qw422016.N().S(goName)
				qw422016.N().S(`) InternalReadTL2(r []byte) (_ []byte, err error) {
    currentSize := 0
    if r, currentSize, err = basictl.TL2ParseSize(r); err != nil { return r, err }
    if currentSize == 0 {
        item.Reset()
        return r, nil
    }
    if len(r) < currentSize {
        return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
    }

    currentR := r[:currentSize]
    r = r[currentSize:]

    var block byte
    if currentR, err = basictl.ByteRead(currentR, &block); err != nil { return currentR, err }
    // read No of constructor
    if block & 1 != 0 {
        var index int
        if currentR, index, err = basictl.TL2ParseSize(currentR); err != nil { return currentR, err }
        if index != 0 {
            return r, `)
				qw422016.N().S(struct_.wr.gen.InternalPrefix())
				qw422016.N().S(`ErrorInvalidUnionIndex(`)
				qw422016.N().Q(tlName)
				qw422016.N().S(`, index)
        }
    }
`)
			} else {
				qw422016.N().S(`func (item *`)
				qw422016.N().S(goName)
				qw422016.N().S(`) InternalReadTL2(r []byte, block byte) (_ []byte, err error) {
    currentR := r
`)
			}
			for _, tl2mask := range struct_.AllNewTL2Masks() {
				qw422016.N().S(`         item.`)
				qw422016.N().S(tl2mask)
				qw422016.N().S(` = 0
`)
			}
			for fieldIndex, field := range struct_.Fields {
				fieldAccess, fieldAsterisk := field.FieldAccess(bytesVersion, directImports, struct_.wr.ins)

				if (fieldIndex+1)%8 == 0 {
					qw422016.N().S(`            // start the next block
    if len(currentR) > 0 {
        if currentR, err = basictl.ByteRead(currentR, &block); err != nil { return currentR, err }
    } else {
        block = 0
    }
`)
				}
				if field.IsBit() {
					if field.MaskTL2Bit() != nil {
						qw422016.N().S(`            if block & `)
						qw422016.E().V(1 << ((fieldIndex + 1) % 8))
						qw422016.N().S(` != 0 {
                item.`)
						qw422016.N().S(field.TL2MaskForOP("|="))
						qw422016.N().S(`
            }
`)
					}
					continue
				}
				if field.IsTL2Omitted() || field.t.IsTrueType() {
					qw422016.N().S(`    if block & `)
					qw422016.E().V(1 << ((fieldIndex + 1) % 8))
					qw422016.N().S(` != 0 {
        `)
					qw422016.N().S(field.t.SkipTL2Call(directImports, bytesVersion, "currentR", field.FieldMask() == nil, struct_.wr.ins, fieldAsterisk))
					qw422016.N().S(`
    }
`)
				} else {
					qw422016.N().S(`    if block & `)
					qw422016.E().V(1 << ((fieldIndex + 1) % 8))
					qw422016.N().S(` != 0 {
`)
					if field.MaskTL2Bit() != nil {
						qw422016.N().S(`            item.`)
						qw422016.N().S(field.TL2MaskForOP("|="))
						qw422016.N().S(`
`)
					}
					qw422016.N().S(`        `)
					qw422016.N().S(field.EnsureRecursive(bytesVersion, directImports, struct_.wr.ins))
					qw422016.N().S(`        `)
					qw422016.N().S(field.t.ReadTL2Call(directImports, bytesVersion, "currentR", fieldAccess, field.FieldMask() == nil, struct_.wr.ins, fieldAsterisk))
					qw422016.N().S(`
    } else {
        `)
					qw422016.N().S(field.TypeResettingCode(bytesVersion, directImports, struct_.wr.ins))
					qw422016.N().S(`
    }
`)
				}
			}
			qw422016.N().S(`    `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`Unused(currentR)
    return r, nil
}
`)
		}
		qw422016.N().S(`
func (item *`)
		qw422016.N().S(goName)
		qw422016.N().S(`) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
`)
		if !struct_.wr.HasTL2() {
			qw422016.N().S(`        return r, `)
			qw422016.N().S(struct_.wr.gen.InternalPrefix())
			qw422016.N().S(`ErrorTL2SerializersNotGenerated(`)
			qw422016.N().Q(tlName)
			qw422016.N().S(`)
`)
		} else {
			if struct_.unionParent != nil {
				qw422016.N().S(`    currentSize := 0
    if r, currentSize, err = basictl.TL2ParseSize(r); err != nil { return r, err }
    if currentSize == 0 {
        item.Reset()
        return r, nil
    }
   	if len(r) < currentSize {
		return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
	}
    currentR := r[:currentSize]
    r = r[currentSize:]

    var block byte
    if currentR, err = basictl.ByteRead(currentR, &block); err != nil { return r, err }
    if (block & 1) != 0 {
        var index int
        if currentR, index, err = basictl.TL2ParseSize(currentR); err != nil { return r, err }
        if index != `)
				qw422016.N().D(struct_.unionIndex)
				qw422016.N().S(` {
            return r, basictl.TL2Error("unexpected constructor number %d, instead of %d", index, `)
				qw422016.N().D(struct_.unionIndex)
				qw422016.N().S(`)
        }
    }
    _, err = item.InternalReadTL2(currentR, block)
    return r, err
`)
			} else {
				qw422016.N().S(`    return item.InternalReadTL2(r)
`)
			}
		}
		qw422016.N().S(`}
`)
	}
}

func (struct_ *TypeRWStruct) writegenerateTL2Code(qq422016 qtio422016.Writer, bytesVersion bool, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	struct_.streamgenerateTL2Code(qw422016, bytesVersion, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (struct_ *TypeRWStruct) generateTL2Code(bytesVersion bool, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	struct_.writegenerateTL2Code(qb422016, bytesVersion, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
