// Code generated by qtc from "qt_factory_bytes.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package tlcodegen

import "fmt"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (gen *Gen2) streamgenerateFactoryBytes(qw422016 *qt422016.Writer, sortedImports []string, directImports *DirectImports) {
	qw422016.N().S(HeaderComment)
	qw422016.N().S(`
`)
	typeWrappers := gen.generatedTypesList

	qw422016.N().S(`package `)
	qw422016.E().S(FactoryGoPackageNameBytes)
	qw422016.N().S(`

import (
    "`)
	qw422016.N().S(gen.MetaPackageName)
	qw422016.N().S(`"
`)
	for _, wr := range sortedImports {
		qw422016.N().S(`    "`)
		qw422016.N().S(gen.options.TLPackageNameFull)
		qw422016.N().S(`/`)
		qw422016.N().S(wr)
		qw422016.N().S(`"
`)
	}
	qw422016.N().S(`)

func CreateFunctionBytes(tag uint32) meta.Function {
    return meta.CreateFunctionBytes(tag)
}

func CreateObjectBytes(tag uint32) meta.Object {
    return meta.CreateObjectBytes(tag)
}

// name can be in any of 3 forms "ch_proxy.insert#7cf362ba", "ch_proxy.insert" or "#7cf362ba"
func CreateFunctionFromNameBytes(name string) meta.Function {
    return meta.CreateFunctionFromNameBytes(name)
}

// name can be in any of 3 forms "ch_proxy.insert#7cf362ba", "ch_proxy.insert" or "#7cf362ba"
func CreateObjectFromNameBytes(name string) meta.Object {
    return meta.CreateObjectFromNameBytes(name)
}

func init() {
`)
	tl1Wrappers, tl2Wrappers := ExtractTopLevelTypes(typeWrappers)

	if len(tl1Wrappers) != 0 {
		qw422016.N().S(`// TL
`)
	}
	for _, wr := range tl1Wrappers {
		hasBytes := wr.wantsBytesVersion && wr.hasBytesVersion

		if wr.tlTag == 0 || !wr.IsTopLevel() {
			continue
		}
		if fun, ok := wr.trw.(*TypeRWStruct); ok && len(wr.NatParams) == 0 {
			tlTag := fmt.Sprintf("0x%08x", wr.tlTag)

			if wr.unionParent != nil && wr.unionParent.IsEnum {
				qw422016.N().S(`            meta.SetGlobalFactoryCreateForEnumElementBytes(`)
				qw422016.E().S(tlTag)
				qw422016.N().S(`)
`)
				continue
			}
			qw422016.N().S(`    `)
			if fun.ResultType != nil {
				qw422016.N().S(`meta.SetGlobalFactoryCreateForFunctionBytes(`)
				qw422016.N().S(tlTag)
				qw422016.N().S(`,func() meta.Object { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(hasBytes, directImports, nil, false, true))
				qw422016.N().S(`; return &ret },func() meta.Function { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(hasBytes, directImports, nil, false, true))
				qw422016.N().S(`; return &ret },`)
				if wr.WrLong != nil {
					qw422016.N().S(`func() meta.Function { var ret`)
					qw422016.N().S(` `)
					qw422016.N().S(wr.WrLong.TypeString2(hasBytes, directImports, nil, false, true))
					qw422016.N().S(`; return &ret },`)
				} else {
					qw422016.N().S(`nil,`)
				}
			} else {
				qw422016.N().S(`meta.SetGlobalFactoryCreateForObjectBytes(`)
				qw422016.N().S(tlTag)
				qw422016.N().S(`,func() meta.Object { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(hasBytes, directImports, nil, false, true))
				qw422016.N().S(`; return &ret }`)
			}
			qw422016.N().S(`)`)
			qw422016.N().S(`
`)
		}
	}
	if len(tl2Wrappers) != 0 {
		qw422016.N().S(`// TL2
`)
	}
	for _, wr := range tl2Wrappers {
		hasBytes := wr.wantsBytesVersion && wr.hasBytesVersion

		if fun, ok := wr.trw.(*TypeRWStruct); ok {
			tlTag := fmt.Sprintf("0x%08x", wr.tlTag)

			if wr.unionParent != nil && wr.unionParent.IsEnum {
				qw422016.N().S(`            meta.SetGlobalFactoryCreateForEnumElementBytes(`)
				qw422016.E().S(tlTag)
				qw422016.N().S(`)
`)
				continue
			}
			qw422016.N().S(`    `)
			if fun.ResultType != nil {
				qw422016.N().S(`meta.SetGlobalFactoryCreateForFunctionBytes(`)
				qw422016.N().S(tlTag)
				qw422016.N().S(`,func() meta.Object { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(hasBytes, directImports, nil, false, true))
				qw422016.N().S(`; return &ret },func() meta.Function { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(hasBytes, directImports, nil, false, true))
				qw422016.N().S(`; return &ret },`)
				if wr.WrLong != nil {
					qw422016.N().S(`func() meta.Function { var ret`)
					qw422016.N().S(` `)
					qw422016.N().S(wr.WrLong.TypeString2(hasBytes, directImports, nil, false, true))
					qw422016.N().S(`; return &ret },`)
				} else {
					qw422016.N().S(`nil,`)
				}
			} else {
				qw422016.N().S(`meta.SetGlobalFactoryCreateForObjectBytesTL2(`)
				qw422016.N().Q(wr.tlName.String())
				qw422016.N().S(`,func() meta.Object { var ret`)
				qw422016.N().S(` `)
				qw422016.N().S(wr.TypeString2(hasBytes, directImports, nil, false, true))
				qw422016.N().S(`; return &ret }`)
			}
			qw422016.N().S(`)`)
			qw422016.N().S(`
`)
		}
		if _, ok := wr.trw.(*TypeRWUnion); ok {
			qw422016.N().S(`    `)
			qw422016.N().S(`meta.SetGlobalFactoryCreateForObjectBytesTL2(`)
			qw422016.N().Q(wr.tlName.String())
			qw422016.N().S(`,func() meta.Object { var ret`)
			qw422016.N().S(` `)
			qw422016.N().S(wr.TypeString2(hasBytes, directImports, nil, false, true))
			qw422016.N().S(`; return &ret })`)
			qw422016.N().S(`
`)
		}
	}
	qw422016.N().S(`}

`)
}

func (gen *Gen2) writegenerateFactoryBytes(qq422016 qtio422016.Writer, sortedImports []string, directImports *DirectImports) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	gen.streamgenerateFactoryBytes(qw422016, sortedImports, directImports)
	qt422016.ReleaseWriter(qw422016)
}

func (gen *Gen2) generateFactoryBytes(sortedImports []string, directImports *DirectImports) string {
	qb422016 := qt422016.AcquireByteBuffer()
	gen.writegenerateFactoryBytes(qb422016, sortedImports, directImports)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
