// Code generated by tl2gen; DO NOT EDIT.
package tl

import (
	"github.com/VKCOM/tl/internal/speed/speed_tl/internal"
)

type (
	PartialPoint            = internal.PartialPoint
	PartialPoints           = internal.PartialPoints
	Point                   = internal.Point
	Points                  = internal.Points
	UnionPoint              = internal.UnionPoint
	UnionPointError         = internal.UnionPointError
	UnionPointValue         = internal.UnionPointValue
	UnionPoints             = internal.UnionPoints
	VectorPartialPointBoxed = internal.VectorPartialPointBoxed
	VectorPointBoxed        = internal.VectorPointBoxed
	VectorUnionPoint        = internal.VectorUnionPoint
)
