// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/tl/internal/speed/speed_tl/basictl"
)

var _ = basictl.NatWrite

type Points struct {
	Values []Point
}

func (Points) TLName() string { return "points" }
func (Points) TLTag() uint32  { return 0xebf9dd56 }

func (item *Points) Reset() {
	item.Values = item.Values[:0]
}

func (item *Points) ReadTL1(w []byte) (_ []byte, err error) {
	return BuiltinVectorPointBoxedReadTL1(w, &item.Values)
}

func (item *Points) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *Points) WriteTL1(w []byte) []byte {
	w = BuiltinVectorPointBoxedWriteTL1(w, item.Values)
	return w
}

func (item *Points) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0xebf9dd56); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *Points) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *Points) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0xebf9dd56)
	return item.WriteTL1(w)
}

func (item Points) String() string {
	return string(item.WriteJSON(nil))
}

func (item *Points) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *Points) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propValuesPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "values":
				if propValuesPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("points", "values")
				}
				propValuesPresented = true
				if err := BuiltinVectorPointBoxedReadJSONGeneral(jctx, in, &item.Values); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("points", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propValuesPresented {
		item.Values = item.Values[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *Points) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *Points) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *Points) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexValues := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"values":`...)
	w = BuiltinVectorPointBoxedWriteJSONOpt(jctx, w, item.Values)
	if !(len(item.Values) != 0) {
		w = w[:backupIndexValues]
	}
	return append(w, '}')
}

func (item *Points) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *Points) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("points", err.Error())
	}
	return nil
}

func (item *Points) CalculateLayout(sizes []int, optimizeEmpty bool) ([]int, int) {
	sizes = append(sizes, 3802914423)
	sizePosition := len(sizes)
	sizes = append(sizes, 0)

	currentSize := 1
	lastUsedByte := 0
	var sz int

	if sizes, sz = BuiltinVectorPointBoxedCalculateLayout(sizes, true, &item.Values); sz != 0 {
		currentSize += sz
		lastUsedByte = currentSize
	}

	if lastUsedByte < currentSize {
		currentSize = lastUsedByte
	}
	sizes[sizePosition] = currentSize
	if currentSize == 0 {
		sizes = sizes[:sizePosition+1]
	}
	if !optimizeEmpty || currentSize != 0 {
		currentSize += basictl.TL2CalculateSize(currentSize)
	}
	Unused(sz)
	return sizes, currentSize
}

func (item *Points) InternalWriteTL2(w []byte, sizes []int, optimizeEmpty bool) ([]byte, []int, int) {
	if sizes[0] != 3802914423 {
		panic("tl2: tag mismatch between calculate and write")
	}
	currentSize := sizes[1]
	sizes = sizes[2:]
	if optimizeEmpty && currentSize == 0 {
		return w, sizes, 0
	}
	w = basictl.TL2WriteSize(w, currentSize)
	if currentSize == 0 {
		return w, sizes, 1
	}
	oldLen := len(w)
	var sz int
	var currentBlock byte
	currentBlockPosition := len(w)
	w = append(w, 0)
	if w, sizes, sz = BuiltinVectorPointBoxedInternalWriteTL2(w, sizes, true, &item.Values); sz != 0 {
		currentBlock |= 2
	}
	if currentBlockPosition < len(w) {
		w[currentBlockPosition] = currentBlock
	}
	if len(w)-oldLen != currentSize {
		panic("tl2: mismatch between calculate and write")
	}
	Unused(sz)
	return w, sizes, 1
}

func (item *Points) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	var sizes, sizes2 []int
	if tctx != nil {
		sizes = tctx.SizeBuffer[:0]
	}
	sizes, _ = item.CalculateLayout(sizes, false)
	w, sizes2, _ = item.InternalWriteTL2(w, sizes, false)
	if len(sizes2) != 0 {
		panic("tl2: internal write did not consume all size data")
	}
	if tctx != nil {
		tctx.SizeBuffer = sizes
	}
	return w
}

func (item *Points) InternalReadTL2(r []byte) (_ []byte, err error) {
	currentSize := 0
	if r, currentSize, err = basictl.TL2ParseSize(r); err != nil {
		return r, err
	}
	if currentSize == 0 {
		item.Reset()
		return r, nil
	}
	if len(r) < currentSize {
		return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
	}

	currentR := r[:currentSize]
	r = r[currentSize:]

	var block byte
	if currentR, err = basictl.ByteRead(currentR, &block); err != nil {
		return currentR, err
	}
	// read No of constructor
	if block&1 != 0 {
		var index int
		if currentR, index, err = basictl.TL2ParseSize(currentR); err != nil {
			return currentR, err
		}
		if index != 0 {
			return r, ErrorInvalidUnionIndex("points", index)
		}
	}
	if block&2 != 0 {
		if currentR, err = BuiltinVectorPointBoxedInternalReadTL2(currentR, &item.Values); err != nil {
			return currentR, err
		}
	} else {
		item.Values = item.Values[:0]
	}
	Unused(currentR)
	return r, nil
}

func (item *Points) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return item.InternalReadTL2(r)
}
