// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/tl/internal/speed/speed_tl/basictl"
)

var _ = basictl.NatWrite

func BuiltinVectorUnionPointRepairMasks(vec *[]UnionPoint) {
	for i := range *vec {
		(*vec)[i].RepairMasks()
	}
}
func BuiltinVectorUnionPointReadTL1(w []byte, vec *[]UnionPoint) (_ []byte, err error) {
	var l uint32
	if w, err = basictl.NatRead(w, &l); err != nil {
		return w, err
	}
	if err = basictl.CheckLengthSanity(w, l, 4); err != nil {
		return w, err
	}
	if uint32(cap(*vec)) < l {
		*vec = make([]UnionPoint, l)
	} else {
		*vec = (*vec)[:l]
	}
	for i := range *vec {
		if w, err = (*vec)[i].ReadTL1Boxed(w); err != nil {
			return w, err
		}
	}
	return w, nil
}

func BuiltinVectorUnionPointWriteTL1(w []byte, vec []UnionPoint) []byte {
	w = basictl.NatWrite(w, uint32(len(vec)))
	for _, elem := range vec {
		w = elem.WriteTL1Boxed(w)
	}
	return w
}

func BuiltinVectorUnionPointCalculateLayout(sizes []int, optimizeEmpty bool, vec *[]UnionPoint) ([]int, int) {
	if len(*vec) == 0 {
		if optimizeEmpty {
			return sizes, 0
		}
		return sizes, 1
	}
	sizePosition := len(sizes)
	sizes = append(sizes, 0)

	currentSize := 0
	var sz int

	currentSize += basictl.TL2CalculateSize(len(*vec))
	for i := 0; i < len(*vec); i++ {
		sizes, sz = (*vec)[i].CalculateLayout(sizes, false)
		currentSize += sz
	}
	sizes[sizePosition] = currentSize
	currentSize += basictl.TL2CalculateSize(currentSize)
	Unused(sz)
	return sizes, currentSize
}

func BuiltinVectorUnionPointInternalWriteTL2(w []byte, sizes []int, optimizeEmpty bool, vec *[]UnionPoint) ([]byte, []int, int) {
	if len(*vec) == 0 {
		if optimizeEmpty {
			return w, sizes, 0
		}
		w = append(w, 0)
		return w, sizes, 1
	}
	currentSize := sizes[0]
	sizes = sizes[1:]
	w = basictl.TL2WriteSize(w, currentSize)
	if currentSize == 0 {
		return w, sizes, 1
	}
	oldLen := len(w)
	w = basictl.TL2WriteSize(w, len(*vec))

	var sz int
	for i := 0; i < len(*vec); i++ {
		w, sizes, _ = (*vec)[i].InternalWriteTL2(w, sizes, false)
	}
	Unused(sz)
	if len(w)-oldLen != currentSize {
		panic("tl2: mismatch between calculate and write")
	}
	return w, sizes, currentSize
}

func BuiltinVectorUnionPointInternalReadTL2(r []byte, vec *[]UnionPoint) (_ []byte, err error) {
	currentSize := 0
	if r, currentSize, err = basictl.TL2ParseSize(r); err != nil {
		return r, err
	}
	if len(r) < currentSize {
		return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
	}

	currentR := r[:currentSize]
	r = r[currentSize:]

	elementCount := 0
	if currentSize != 0 {
		if currentR, elementCount, err = basictl.TL2ParseSize(currentR); err != nil {
			return r, err
		}
		if elementCount > len(currentR) {
			return r, basictl.TL2ElementCountError(elementCount, currentR)
		}
	}

	if cap(*vec) < elementCount {
		*vec = make([]UnionPoint, elementCount)
	}
	*vec = (*vec)[:elementCount]
	for i := 0; i < elementCount; i++ {
		if currentR, err = (*vec)[i].InternalReadTL2(currentR); err != nil {
			return currentR, err
		}
	}
	return r, nil
}

func BuiltinVectorUnionPointReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, vec *[]UnionPoint) error {
	*vec = (*vec)[:cap(*vec)]
	index := 0
	if in != nil {
		in.Delim('[')
		if !in.Ok() {
			return ErrorInvalidJSON("[]UnionPoint", "expected json array")
		}
		for ; !in.IsDelim(']'); index++ {
			if len(*vec) <= index {
				var newValue UnionPoint
				*vec = append(*vec, newValue)
				*vec = (*vec)[:cap(*vec)]
			}
			if err := (*vec)[index].ReadJSONGeneral(jctx, in); err != nil {
				return err
			}
			in.WantComma()
		}
		in.Delim(']')
		if !in.Ok() {
			return ErrorInvalidJSON("[]UnionPoint", "expected json array's end")
		}
	}
	*vec = (*vec)[:index]
	return nil
}

func BuiltinVectorUnionPointWriteJSON(w []byte, vec []UnionPoint) []byte {
	return BuiltinVectorUnionPointWriteJSONOpt(nil, w, vec)
}
func BuiltinVectorUnionPointWriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte, vec []UnionPoint) []byte {
	w = append(w, '[')
	for _, elem := range vec {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = elem.WriteJSONOpt(jctx, w)
	}
	return append(w, ']')
}

var _UnionPoint = [2]UnionElement{
	{TLTag: 0xbee8f76b, TLName: "unionPointValue", TLString: "unionPointValue#bee8f76b"},
	{TLTag: 0xa8dbfd23, TLName: "unionPointError", TLString: "unionPointError#a8dbfd23"},
}

type UnionPoint struct {
	valueValue UnionPointValue
	valueError UnionPointError
	index      int
}

func (item UnionPoint) TLName() string { return _UnionPoint[item.index].TLName }
func (item UnionPoint) TLTag() uint32  { return _UnionPoint[item.index].TLTag }

func (item *UnionPoint) Reset() { item.ResetToValue() }
func (item UnionPoint) RepairMasksValue() UnionPoint {
	item.RepairMasks()
	return item
}
func (item *UnionPoint) RepairMasks() {
	item.valueValue.RepairMasks()
}

func (item *UnionPoint) IsValue() bool { return item.index == 0 }

func (item *UnionPoint) AsValue() (*UnionPointValue, bool) {
	if item.index != 0 {
		return nil, false
	}
	return &item.valueValue, true
}
func (item *UnionPoint) ResetToValue() *UnionPointValue {
	item.index = 0
	item.valueValue.Reset()
	return &item.valueValue
}
func (item *UnionPoint) SetValue(value UnionPointValue) {
	item.index = 0
	item.valueValue = value
}

func (item *UnionPoint) IsError() bool { return item.index == 1 }

func (item *UnionPoint) AsError() (*UnionPointError, bool) {
	if item.index != 1 {
		return nil, false
	}
	return &item.valueError, true
}
func (item *UnionPoint) ResetToError() *UnionPointError {
	item.index = 1
	item.valueError.Reset()
	return &item.valueError
}
func (item *UnionPoint) SetError(value UnionPointError) {
	item.index = 1
	item.valueError = value
}

func (item *UnionPoint) ReadTL1(w []byte) (_ []byte, err error) {
	return item.ReadTL1Boxed(w)
}

func (item *UnionPoint) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	var tag uint32
	if w, err = basictl.NatRead(w, &tag); err != nil {
		return w, err
	}
	switch tag {
	case 0xbee8f76b:
		item.index = 0
		return item.valueValue.ReadTL1(w)
	case 0xa8dbfd23:
		item.index = 1
		return item.valueError.ReadTL1(w)
	default:
		return w, ErrorInvalidUnionTag("UnionPoint", tag)
	}
}

func (item *UnionPoint) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1BoxedGeneral(w)
}

func (item *UnionPoint) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *UnionPoint) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, _UnionPoint[item.index].TLTag)
	switch item.index {
	case 0:
		w = item.valueValue.WriteTL1(w)
	case 1:
		w = item.valueError.WriteTL1(w)
	}
	return w
}

func (item *UnionPoint) CalculateLayout(sizes []int, optimizeEmpty bool) ([]int, int) {

	switch item.index {
	case 0:
		return item.valueValue.CalculateLayout(sizes, optimizeEmpty)
	case 1:
		return item.valueError.CalculateLayout(sizes, optimizeEmpty)
	}
	if item.index == 0 {
		if optimizeEmpty {
			return sizes, 0
		}
		return sizes, 1
	}
	bodySize := 1 + basictl.TL2CalculateSize(item.index)
	return sizes, 1 + bodySize
}

func (item *UnionPoint) InternalWriteTL2(w []byte, sizes []int, optimizeEmpty bool) ([]byte, []int, int) {

	switch item.index {
	case 0:
		return item.valueValue.InternalWriteTL2(w, sizes, optimizeEmpty)
	case 1:
		return item.valueError.InternalWriteTL2(w, sizes, optimizeEmpty)
	}
	if item.index == 0 {
		if optimizeEmpty {
			return w, sizes, 0
		}
		w = append(w, 0)
		return w, sizes, 1
	}
	bodySize := 1 + basictl.TL2CalculateSize(item.index)
	w = append(w, byte(bodySize))
	w = append(w, 1)
	w = basictl.TL2WriteSize(w, item.index)
	return w, sizes, 1 + bodySize
}

func (item *UnionPoint) InternalReadTL2(r []byte) (_ []byte, err error) {
	currentSize := 0
	if r, currentSize, err = basictl.TL2ParseSize(r); err != nil {
		return r, err
	}
	if currentSize == 0 {
		item.Reset()
		return r, nil
	}
	if len(r) < currentSize {
		return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
	}
	currentR := r[:currentSize]
	r = r[currentSize:]

	var block byte
	if currentR, err = basictl.ByteRead(currentR, &block); err != nil {
		return r, err
	}
	item.index = 0
	if (block & 1) != 0 {
		if currentR, item.index, err = basictl.TL2ParseSize(currentR); err != nil {
			return r, err
		}
		if item.index >= 2 {
			return r, ErrorInvalidUnionIndex("UnionPoint", item.index)
		}
	}
	switch item.index {
	case 0:
		if currentR, err = item.valueValue.InternalReadTL2(currentR, block); err != nil {
			return currentR, err
		}
	case 1:
		if currentR, err = item.valueError.InternalReadTL2(currentR, block); err != nil {
			return currentR, err
		}
	}
	Unused(currentR)
	return r, nil
}
func (item *UnionPoint) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	var sizes, sizes2 []int
	if tctx != nil {
		sizes = tctx.SizeBuffer[:0]
	}
	sizes, _ = item.CalculateLayout(sizes, false)
	w, sizes2, _ = item.InternalWriteTL2(w, sizes, false)
	if len(sizes2) != 0 {
		panic("tl2: internal write did not consume all size data")
	}
	if tctx != nil {
		tctx.SizeBuffer = sizes
	}
	return w
}

func (item *UnionPoint) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) ([]byte, error) {
	return item.InternalReadTL2(r)
}

func (item *UnionPoint) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *UnionPoint) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	_tag, _value, err := Json2ReadUnion("UnionPoint", in)
	if err != nil {
		return err
	}
	switch _tag {
	case "Value", "unionPointValue#bee8f76b", "unionPointValue", "#bee8f76b":
		if jctx != nil && !jctx.LegacyTypeNames && _tag == "unionPointValue#bee8f76b" {
			return ErrorInvalidUnionLegacyTagJSON("UnionPoint", "unionPointValue#bee8f76b")
		}
		if jctx != nil && !jctx.LegacyTypeNames && _tag == "#bee8f76b" {
			return ErrorInvalidUnionLegacyTagJSON("UnionPoint", "#bee8f76b")
		}
		item.index = 0
		var in2Pointer *basictl.JsonLexer
		if _value != nil {
			in2Pointer = &basictl.JsonLexer{Data: _value}
		}
		if err := item.valueValue.ReadJSONGeneral(jctx, in2Pointer); err != nil {
			return err
		}
	case "Error", "unionPointError#a8dbfd23", "unionPointError", "#a8dbfd23":
		if jctx != nil && !jctx.LegacyTypeNames && _tag == "unionPointError#a8dbfd23" {
			return ErrorInvalidUnionLegacyTagJSON("UnionPoint", "unionPointError#a8dbfd23")
		}
		if jctx != nil && !jctx.LegacyTypeNames && _tag == "#a8dbfd23" {
			return ErrorInvalidUnionLegacyTagJSON("UnionPoint", "#a8dbfd23")
		}
		item.index = 1
		var in2Pointer *basictl.JsonLexer
		if _value != nil {
			in2Pointer = &basictl.JsonLexer{Data: _value}
		}
		if err := item.valueError.ReadJSONGeneral(jctx, in2Pointer); err != nil {
			return err
		}
	default:
		return ErrorInvalidUnionTagJSON("UnionPoint", _tag)
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *UnionPoint) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) ([]byte, error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *UnionPoint) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *UnionPoint) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	switch item.index {
	case 0:
		if jctx != nil && jctx.IsTL2 {
			w = append(w, `{"type":"Value"`...)
		} else {
			if jctx != nil && jctx.LegacyTypeNames {
				w = append(w, `{"type":"unionPointValue#bee8f76b"`...)
			} else {
				w = append(w, `{"type":"unionPointValue"`...)
			}
		}
		w = append(w, `,"value":`...)
		w = item.valueValue.WriteJSONOpt(jctx, w)
		return append(w, '}')
	case 1:
		if jctx != nil && jctx.IsTL2 {
			w = append(w, `{"type":"Error"`...)
		} else {
			if jctx != nil && jctx.LegacyTypeNames {
				w = append(w, `{"type":"unionPointError#a8dbfd23"`...)
			} else {
				w = append(w, `{"type":"unionPointError"`...)
			}
		}
		w = append(w, `,"value":`...)
		w = item.valueError.WriteJSONOpt(jctx, w)
		return append(w, '}')
	default: // Impossible due to panic above
		return w
	}
}

func (item UnionPoint) String() string {
	return string(item.WriteJSON(nil))
}

func (item *UnionPoint) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *UnionPoint) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("UnionPoint", err.Error())
	}
	return nil
}

func (item UnionPointError) AsUnion() UnionPoint {
	var ret UnionPoint
	ret.SetError(item)
	return ret
}

type UnionPointError struct {
	Err string
}

func (UnionPointError) TLName() string { return "unionPointError" }
func (UnionPointError) TLTag() uint32  { return 0xa8dbfd23 }

func (item *UnionPointError) Reset() {
	item.Err = ""
}

func (item *UnionPointError) ReadTL1(w []byte) (_ []byte, err error) {
	return basictl.StringRead(w, &item.Err)
}

func (item *UnionPointError) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *UnionPointError) WriteTL1(w []byte) []byte {
	w = basictl.StringWrite(w, item.Err)
	return w
}

func (item *UnionPointError) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0xa8dbfd23); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *UnionPointError) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *UnionPointError) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0xa8dbfd23)
	return item.WriteTL1(w)
}

func (item UnionPointError) String() string {
	return string(item.WriteJSON(nil))
}

func (item *UnionPointError) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *UnionPointError) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propErrPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "err":
				if propErrPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("unionPointError", "err")
				}
				propErrPresented = true
				if err := Json2ReadString(in, &item.Err); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("unionPointError", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propErrPresented {
		item.Err = ""
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *UnionPointError) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *UnionPointError) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *UnionPointError) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexErr := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"err":`...)
	w = basictl.JSONWriteString(w, item.Err)
	if !(len(item.Err) != 0) {
		w = w[:backupIndexErr]
	}
	return append(w, '}')
}

func (item *UnionPointError) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *UnionPointError) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("unionPointError", err.Error())
	}
	return nil
}

func (item *UnionPointError) CalculateLayout(sizes []int, optimizeEmpty bool) ([]int, int) {
	sizes = append(sizes, 2471129417)
	sizePosition := len(sizes)
	sizes = append(sizes, 0)

	currentSize := 1
	lastUsedByte := 0
	var sz int

	// add constructor No for union type in case of non first option
	currentSize += basictl.TL2CalculateSize(1)
	lastUsedByte = currentSize
	if len(item.Err) != 0 {
		currentSize += basictl.TL2CalculateSize(len(item.Err)) + len(item.Err)
		lastUsedByte = currentSize
	}

	if lastUsedByte < currentSize {
		currentSize = lastUsedByte
	}
	sizes[sizePosition] = currentSize
	if currentSize == 0 {
		sizes = sizes[:sizePosition+1]
	}
	if !optimizeEmpty || currentSize != 0 {
		currentSize += basictl.TL2CalculateSize(currentSize)
	}
	Unused(sz)
	return sizes, currentSize
}

func (item *UnionPointError) InternalWriteTL2(w []byte, sizes []int, optimizeEmpty bool) ([]byte, []int, int) {
	if sizes[0] != 2471129417 {
		panic("tl2: tag mismatch between calculate and write")
	}
	currentSize := sizes[1]
	sizes = sizes[2:]
	if optimizeEmpty && currentSize == 0 {
		return w, sizes, 0
	}
	w = basictl.TL2WriteSize(w, currentSize)
	if currentSize == 0 {
		return w, sizes, 1
	}
	oldLen := len(w)
	var sz int
	var currentBlock byte
	currentBlockPosition := len(w)
	w = append(w, 0)
	w = basictl.TL2WriteSize(w, 1)
	currentBlock |= 1
	if len(item.Err) != 0 {
		w = basictl.StringWriteTL2(w, item.Err)
		currentBlock |= 2
	}
	if currentBlockPosition < len(w) {
		w[currentBlockPosition] = currentBlock
	}
	if len(w)-oldLen != currentSize {
		panic("tl2: mismatch between calculate and write")
	}
	Unused(sz)
	return w, sizes, 1
}

func (item *UnionPointError) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	var sizes, sizes2 []int
	if tctx != nil {
		sizes = tctx.SizeBuffer[:0]
	}
	sizes, _ = item.CalculateLayout(sizes, false)
	w, sizes2, _ = item.InternalWriteTL2(w, sizes, false)
	if len(sizes2) != 0 {
		panic("tl2: internal write did not consume all size data")
	}
	if tctx != nil {
		tctx.SizeBuffer = sizes
	}
	return w
}

func (item *UnionPointError) InternalReadTL2(r []byte, block byte) (_ []byte, err error) {
	currentR := r
	if block&2 != 0 {
		if currentR, err = basictl.StringReadTL2(currentR, &item.Err); err != nil {
			return currentR, err
		}
	} else {
		item.Err = ""
	}
	Unused(currentR)
	return r, nil
}

func (item *UnionPointError) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	currentSize := 0
	if r, currentSize, err = basictl.TL2ParseSize(r); err != nil {
		return r, err
	}
	if currentSize == 0 {
		item.Reset()
		return r, nil
	}
	if len(r) < currentSize {
		return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
	}
	currentR := r[:currentSize]
	r = r[currentSize:]

	var block byte
	if currentR, err = basictl.ByteRead(currentR, &block); err != nil {
		return r, err
	}
	if (block & 1) != 0 {
		var index int
		if currentR, index, err = basictl.TL2ParseSize(currentR); err != nil {
			return r, err
		}
		if index != 1 {
			return r, basictl.TL2Error("unexpected constructor number %d, instead of %d", index, 1)
		}
	}
	_, err = item.InternalReadTL2(currentR, block)
	return r, err
}

func (item UnionPointValue) AsUnion() UnionPoint {
	var ret UnionPoint
	ret.SetValue(item)
	return ret
}

type UnionPointValue struct {
	Mask     uint32
	X        uint32 // Conditional: item.Mask.0
	Y        uint32 // Conditional: item.Mask.1
	Z        uint32 // Conditional: item.Mask.2
	tl2mask0 byte
}

func (UnionPointValue) TLName() string { return "unionPointValue" }
func (UnionPointValue) TLTag() uint32  { return 0xbee8f76b }

func (item *UnionPointValue) SetX(v uint32) {
	item.X = v
	item.Mask |= 1 << 0
	item.tl2mask0 |= 1
}
func (item *UnionPointValue) ClearX() {
	item.X = 0
	item.Mask &^= 1 << 0
	item.tl2mask0 &^= 1
}
func (item *UnionPointValue) IsSetX() bool { return item.tl2mask0&1 != 0 }

func (item *UnionPointValue) SetY(v uint32) {
	item.Y = v
	item.Mask |= 1 << 1
	item.tl2mask0 |= 2
}
func (item *UnionPointValue) ClearY() {
	item.Y = 0
	item.Mask &^= 1 << 1
	item.tl2mask0 &^= 2
}
func (item *UnionPointValue) IsSetY() bool { return item.tl2mask0&2 != 0 }

func (item *UnionPointValue) SetZ(v uint32) {
	item.Z = v
	item.Mask |= 1 << 2
	item.tl2mask0 |= 4
}
func (item *UnionPointValue) ClearZ() {
	item.Z = 0
	item.Mask &^= 1 << 2
	item.tl2mask0 &^= 4
}
func (item *UnionPointValue) IsSetZ() bool { return item.tl2mask0&4 != 0 }

func (item *UnionPointValue) Reset() {
	item.Mask = 0
	item.X = 0
	item.Y = 0
	item.Z = 0
	item.tl2mask0 = 0
}

func (item UnionPointValue) RepairMasksValue() UnionPointValue {
	item.RepairMasks()
	return item
}
func (item *UnionPointValue) RepairMasks() {
	item.tl2mask0 = 0
	if item.Mask&(1<<0) != 0 {
		item.tl2mask0 |= 1
	}
	if item.Mask&(1<<1) != 0 {
		item.tl2mask0 |= 2
	}
	if item.Mask&(1<<2) != 0 {
		item.tl2mask0 |= 4
	}
}

func (item *UnionPointValue) ReadTL1(w []byte) (_ []byte, err error) {
	item.tl2mask0 = 0
	if w, err = basictl.NatRead(w, &item.Mask); err != nil {
		return w, err
	}
	if item.Mask&(1<<0) != 0 {
		item.tl2mask0 |= 1
		if w, err = basictl.NatRead(w, &item.X); err != nil {
			return w, err
		}
	} else {
		item.X = 0
	}
	if item.Mask&(1<<1) != 0 {
		item.tl2mask0 |= 2
		if w, err = basictl.NatRead(w, &item.Y); err != nil {
			return w, err
		}
	} else {
		item.Y = 0
	}
	if item.Mask&(1<<2) != 0 {
		item.tl2mask0 |= 4
		if w, err = basictl.NatRead(w, &item.Z); err != nil {
			return w, err
		}
	} else {
		item.Z = 0
	}
	return w, nil
}

func (item *UnionPointValue) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *UnionPointValue) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.Mask)
	if item.Mask&(1<<0) != 0 {
		w = basictl.NatWrite(w, item.X)
	}
	if item.Mask&(1<<1) != 0 {
		w = basictl.NatWrite(w, item.Y)
	}
	if item.Mask&(1<<2) != 0 {
		w = basictl.NatWrite(w, item.Z)
	}
	return w
}

func (item *UnionPointValue) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0xbee8f76b); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *UnionPointValue) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *UnionPointValue) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0xbee8f76b)
	return item.WriteTL1(w)
}

func (item UnionPointValue) String() string {
	return string(item.WriteJSON(nil))
}

func (item *UnionPointValue) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *UnionPointValue) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	item.tl2mask0 = 0
	var propMaskPresented bool
	var propXPresented bool
	var propYPresented bool
	var propZPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "mask":
				if propMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("unionPointValue", "mask")
				}
				propMaskPresented = true
				if err := Json2ReadUint32(in, &item.Mask); err != nil {
					return err
				}
			case "x":
				if propXPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("unionPointValue", "x")
				}
				propXPresented = true
				if err := Json2ReadUint32(in, &item.X); err != nil {
					return err
				}
				item.tl2mask0 |= 1
			case "y":
				if propYPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("unionPointValue", "y")
				}
				propYPresented = true
				if err := Json2ReadUint32(in, &item.Y); err != nil {
					return err
				}
				item.tl2mask0 |= 2
			case "z":
				if propZPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("unionPointValue", "z")
				}
				propZPresented = true
				if err := Json2ReadUint32(in, &item.Z); err != nil {
					return err
				}
				item.tl2mask0 |= 4
			default:
				return ErrorInvalidJSONExcessElement("unionPointValue", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propMaskPresented {
		item.Mask = 0
	}
	if !propXPresented {
		item.X = 0
	}
	if !propYPresented {
		item.Y = 0
	}
	if !propZPresented {
		item.Z = 0
	}
	if !propXPresented && item.Mask&(1<<0) != 0 {
		item.tl2mask0 |= 1
	}
	if !propYPresented && item.Mask&(1<<1) != 0 {
		item.tl2mask0 |= 2
	}
	if !propZPresented && item.Mask&(1<<2) != 0 {
		item.tl2mask0 |= 4
	}
	if propXPresented {
		item.Mask |= 1 << 0
	}
	if propYPresented {
		item.Mask |= 1 << 1
	}
	if propZPresented {
		item.Mask |= 1 << 2
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *UnionPointValue) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *UnionPointValue) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *UnionPointValue) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"mask":`...)
	w = basictl.JSONWriteUint32(w, item.Mask)
	if !(item.Mask != 0) {
		w = w[:backupIndexMask]
	}
	if item.tl2mask0&1 != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"x":`...)
		w = basictl.JSONWriteUint32(w, item.X)
	}
	if item.tl2mask0&2 != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"y":`...)
		w = basictl.JSONWriteUint32(w, item.Y)
	}
	if item.tl2mask0&4 != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"z":`...)
		w = basictl.JSONWriteUint32(w, item.Z)
	}
	return append(w, '}')
}

func (item *UnionPointValue) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *UnionPointValue) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("unionPointValue", err.Error())
	}
	return nil
}

func (item *UnionPointValue) CalculateLayout(sizes []int, optimizeEmpty bool) ([]int, int) {
	sizes = append(sizes, 1766814431)
	sizePosition := len(sizes)
	sizes = append(sizes, 0)

	currentSize := 1
	lastUsedByte := 0
	var sz int

	if item.Mask != 0 {
		currentSize += 4
		lastUsedByte = currentSize
	}
	if item.tl2mask0&1 != 0 {
		currentSize += 4
		lastUsedByte = currentSize
	}
	if item.tl2mask0&2 != 0 {
		currentSize += 4
		lastUsedByte = currentSize
	}
	if item.tl2mask0&4 != 0 {
		currentSize += 4
		lastUsedByte = currentSize
	}

	if lastUsedByte < currentSize {
		currentSize = lastUsedByte
	}
	sizes[sizePosition] = currentSize
	if currentSize == 0 {
		sizes = sizes[:sizePosition+1]
	}
	if !optimizeEmpty || currentSize != 0 {
		currentSize += basictl.TL2CalculateSize(currentSize)
	}
	Unused(sz)
	return sizes, currentSize
}

func (item *UnionPointValue) InternalWriteTL2(w []byte, sizes []int, optimizeEmpty bool) ([]byte, []int, int) {
	if sizes[0] != 1766814431 {
		panic("tl2: tag mismatch between calculate and write")
	}
	currentSize := sizes[1]
	sizes = sizes[2:]
	if optimizeEmpty && currentSize == 0 {
		return w, sizes, 0
	}
	w = basictl.TL2WriteSize(w, currentSize)
	if currentSize == 0 {
		return w, sizes, 1
	}
	oldLen := len(w)
	var sz int
	var currentBlock byte
	currentBlockPosition := len(w)
	w = append(w, 0)
	if item.Mask != 0 {
		w = basictl.NatWrite(w, item.Mask)
		currentBlock |= 2
	}
	if item.tl2mask0&1 != 0 {
		w = basictl.NatWrite(w, item.X)
		currentBlock |= 4
	}
	if item.tl2mask0&2 != 0 {
		w = basictl.NatWrite(w, item.Y)
		currentBlock |= 8
	}
	if item.tl2mask0&4 != 0 {
		w = basictl.NatWrite(w, item.Z)
		currentBlock |= 16
	}
	if currentBlockPosition < len(w) {
		w[currentBlockPosition] = currentBlock
	}
	if len(w)-oldLen != currentSize {
		panic("tl2: mismatch between calculate and write")
	}
	Unused(sz)
	return w, sizes, 1
}

func (item *UnionPointValue) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	var sizes, sizes2 []int
	if tctx != nil {
		sizes = tctx.SizeBuffer[:0]
	}
	sizes, _ = item.CalculateLayout(sizes, false)
	w, sizes2, _ = item.InternalWriteTL2(w, sizes, false)
	if len(sizes2) != 0 {
		panic("tl2: internal write did not consume all size data")
	}
	if tctx != nil {
		tctx.SizeBuffer = sizes
	}
	return w
}

func (item *UnionPointValue) InternalReadTL2(r []byte, block byte) (_ []byte, err error) {
	currentR := r
	item.tl2mask0 = 0
	if block&2 != 0 {
		if currentR, err = basictl.NatRead(currentR, &item.Mask); err != nil {
			return currentR, err
		}
	} else {
		item.Mask = 0
	}
	if block&4 != 0 {
		item.tl2mask0 |= 1
		if currentR, err = basictl.NatRead(currentR, &item.X); err != nil {
			return currentR, err
		}
	} else {
		item.X = 0
	}
	if block&8 != 0 {
		item.tl2mask0 |= 2
		if currentR, err = basictl.NatRead(currentR, &item.Y); err != nil {
			return currentR, err
		}
	} else {
		item.Y = 0
	}
	if block&16 != 0 {
		item.tl2mask0 |= 4
		if currentR, err = basictl.NatRead(currentR, &item.Z); err != nil {
			return currentR, err
		}
	} else {
		item.Z = 0
	}
	Unused(currentR)
	return r, nil
}

func (item *UnionPointValue) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	currentSize := 0
	if r, currentSize, err = basictl.TL2ParseSize(r); err != nil {
		return r, err
	}
	if currentSize == 0 {
		item.Reset()
		return r, nil
	}
	if len(r) < currentSize {
		return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
	}
	currentR := r[:currentSize]
	r = r[currentSize:]

	var block byte
	if currentR, err = basictl.ByteRead(currentR, &block); err != nil {
		return r, err
	}
	if (block & 1) != 0 {
		var index int
		if currentR, index, err = basictl.TL2ParseSize(currentR); err != nil {
			return r, err
		}
		if index != 0 {
			return r, basictl.TL2Error("unexpected constructor number %d, instead of %d", index, 0)
		}
	}
	_, err = item.InternalReadTL2(currentR, block)
	return r, err
}
