name: "CI"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths: ['**.qtpl', '**.go', 'go.mod', 'go.sum']
jobs:
  ci-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          install-go: false