// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package genrust

import (
	"fmt"
	"path/filepath"
	"slices"
	"strings"

	"github.com/VKCOM/tl/internal/pure"
	"github.com/VKCOM/tl/internal/puregen"
	"github.com/VKCOM/tl/internal/tlast"
)

const HeaderComment = "// Code generated by tl2gen; DO NOT EDIT."

type genRust struct {
	kernel  *pure.Kernel
	options *puregen.Options

	bytesWhiteList      pure.Whitelist
	rawHandlerWhileList pure.Whitelist

	generatedTypes     map[string]*TypeRWWrapper
	generatedTypesList []*TypeRWWrapper // we need more deterministic order than sort predicate can establish

	globalDec  puregen.Deconflicter
	Namespaces map[string]*Namespace // Handlers Code is inside
}

func Generate(kernel *pure.Kernel, options *puregen.Options) error {
	options.Kernel.InstantiateConstants = true
	// uncomment for testing behavior relevant for PHP generator
	// options.Kernel.InstantiateExclamationWrappers = true
	if err := kernel.Compile(); err != nil {
		return err
	}
	gen := genRust{
		kernel:         kernel,
		options:        options,
		Namespaces:     map[string]*Namespace{},
		generatedTypes: map[string]*TypeRWWrapper{},
	}
	gen.bytesWhiteList = pure.NewWhiteList("--generateByteVersions", options.BytesWhiteList)
	gen.rawHandlerWhileList = pure.NewWhiteList("--rawHandlerWhiteList", options.Go.RawHandlerWhileList)
	if err := gen.compile(); err != nil {
		return err
	}
	if err := gen.generateCode(); err != nil {
		return err
	}
	if err := gen.bytesWhiteList.UnusedWarning(); err != nil {
		fmt.Printf("%v\n", err)
	}
	if err := gen.rawHandlerWhileList.UnusedWarning(); err != nil {
		fmt.Printf("%v\n", err)
	}
	return nil
}

func (gen *genRust) generateCode() error {
	typesCounter := 0

	var outdir puregen.OutDir

	var s strings.Builder
	for _, typeRw := range gen.generatedTypesList {
		typesCounter++
		s.WriteString("\n")
		directImports := &DirectImports{}
		code := typeRw.trw.GenerateCode(false, directImports)
		s.WriteString(code)
		if code != "" {
			filepathName := filepath.Join("internal", typeRw.fileName+".go")
			if err := outdir.AddCodeFile(filepathName, gen.options.CopyrightText+s.String()); err != nil {
				return err
			}
		}
		s.Reset()
	}
	if gen.options.Kernel.Verbose {
		fmt.Printf("generation of serialization code finished, %d types generated\n", typesCounter)
	}
	for name, namespace := range gen.Namespaces {
		slices.SortFunc(namespace.types, func(a, b *TypeRWWrapper) int {
			return TypeRWWrapperLessLocal(a, b)
		})
		anyTypeAlias := false
		anyEnumElementAlias := false
		anyFunction := false
		for _, wr := range namespace.types {
			if wr.ShouldWriteTypeAlias() {
				anyTypeAlias = true
			}
			if wr.ShouldWriteEnumElementAlias() {
				anyEnumElementAlias = true
			}
			if fun, ok := wr.trw.(*TypeRWStruct); ok && fun.ResultType != nil {
				anyFunction = true
			}
		}
		if !anyTypeAlias && !anyEnumElementAlias && !anyFunction {
			continue
		}
		directImports := &DirectImports{}
		filepathName := filepath.Join(gen.options.Rust.CrateName+name, gen.options.Rust.CrateName+name+".go")
		code := gen.generateNamespacesCode(anyTypeAlias, anyFunction, name, namespace, nil, directImports)
		if code == "" {
			continue
		}
		if err := outdir.AddCodeFile(filepathName, gen.options.CopyrightText+code); err != nil {
			return err
		}
	}
	if gen.options.Kernel.Verbose {
		fmt.Printf("generation of RPC code finished, %d namespaces generated\n", len(gen.Namespaces))
	}
	//{
	//	filepathName := filepath.Join(ConstantsPackageName, ConstantsPackageName+".go") // TODO if contains GlobalPackgeName as prefix, there could be name collisions
	//	code := gen.generateConstants(HeaderComment, ConstantsPackageName)
	//	if err := outdir.AddCodeFile(filepathName, gen.options.CopyrightText+code); err != nil {
	//		return err
	//	}
	//	if gen.BasicPackageRelativePath != "" {
	//		// TODO if contains GlobalPackgeName as prefix, there could be name collisions
	//		filepathName := filepath.Join(gen.BasicPackageRelativePath, "basictl"+".go")
	//		code = basictl.BasicTLContent(HeaderComment, BasicTLGoPackageName)
	//		if err := outdir.AddCodeFile(filepathName, gen.options.CopyrightText+code); err != nil {
	//			return err
	//		}
	//		filepathName = filepath.Join(gen.BasicPackageRelativePath, "basictl2"+".go")
	//		code = basictl.BasicTL2Content(HeaderComment, BasicTLGoPackageName)
	//		if err := outdir.AddCodeFile(filepathName, gen.options.CopyrightText+code); err != nil {
	//			return err
	//		}
	//	} else if gen.options.Kernel.Verbose {
	//		fmt.Printf("basictl code not written, expected to be available at %q\n", gen.options.Go.BasicPackageNameFull)
	//	}
	//	startsWithAnyLetter := func(ns string) bool {
	//		for letter := byte('a'); letter <= 'z'; letter++ {
	//			if len(ns) != 0 && ns[0] == letter {
	//				return true
	//			}
	//		}
	//		return false
	//	}
	//	for _, bytesVersion := range []bool{false, true} {
	//		genFac := func(fileName string, addHeader bool, forNamespace func(ns string) bool) error {
	//			hasCode := false
	//			directImports := &DirectImports{ns: map[*InternalNamespace]struct{}{}}
	//			var sortedNames []string
	//			_ = gen.generateFactory(sortedNames, directImports, bytesVersion,
	//				addHeader, forNamespace, &hasCode)
	//			if !hasCode {
	//				return nil
	//			}
	//			for im := range directImports.ns { // Imports of this file.
	//				sortedNames = append(sortedNames, im.SubPath)
	//			}
	//			slices.Sort(sortedNames)
	//			factoryCode := gen.generateFactory(sortedNames, directImports, bytesVersion,
	//				addHeader, forNamespace, &hasCode)
	//			return outdir.AddCodeFile(filepath.Join(addBytesLower(FactoryGoPackageName, bytesVersion), fileName), gen.options.CopyrightText+factoryCode)
	//		}
	//		if err := genFac(FactoryGoPackageName+".go", true, func(ns string) bool {
	//			return !gen.options.Go.SplitInternal || !startsWithAnyLetter(ns)
	//		}); err != nil {
	//			return err
	//		}
	//		for letter := byte('a'); letter <= 'z'; letter++ {
	//			if err := genFac(string(letter)+".go", false, func(ns string) bool {
	//				return gen.options.Go.SplitInternal && len(ns) != 0 && ns[0] == letter
	//			}); err != nil {
	//				return err
	//			}
	//		}
	//	}
	//	if gen.options.Go.SplitInternal {
	//		metaCode := gen.generateMetaMini(utils.AppVersion())
	//		if err := outdir.AddCodeFile(filepath.Join(MetaGoPackageNameMini, MetaGoPackageName+".go"), gen.options.CopyrightText+metaCode); err != nil {
	//			return err
	//		}
	//	}
	//	metaCode := gen.generateMeta(utils.AppVersion())
	//	metaCode += gen.generateMetaInit(false, gen.generatedTypesList, func(ns string) bool {
	//		return !gen.options.Go.SplitInternal || !startsWithAnyLetter(ns)
	//	}, nil, MetaGoPackageName)
	//
	//	if err := outdir.AddCodeFile(filepath.Join(MetaGoPackageName, MetaGoPackageName+".go"), gen.options.CopyrightText+metaCode); err != nil {
	//		return err
	//	}
	//	for letter := byte('a'); letter <= 'z'; letter++ {
	//		hasTypes := false
	//		metaCode := gen.generateMetaInit(true, gen.generatedTypesList, func(ns string) bool {
	//			return gen.options.Go.SplitInternal && len(ns) != 0 && ns[0] == letter
	//		}, &hasTypes, MetaGoPackageName)
	//		if hasTypes {
	//			if err := outdir.AddCodeFile(filepath.Join(MetaGoPackageName, string(letter)+".go"), gen.options.CopyrightText+metaCode); err != nil {
	//				return err
	//			}
	//		}
	//	}
	//	filepathName = filepath.Join("internal", "a_tlgen_helpers_code.go")
	//	code = gen.generateHelpers(HeaderComment, "internal")
	//
	//	if err := outdir.AddCodeFile(filepathName, gen.options.CopyrightText+code); err != nil {
	//		return err
	//	}
	//	filepathName = filepath.Join("internal/metainternal", "metainternal.go")
	//	code = gen.generateMetaInternal(HeaderComment)
	//
	//	if err := outdir.AddCodeFile(filepathName, gen.options.CopyrightText+code); err != nil {
	//		return err
	//	}
	//}
	filepathName := "Cargo.toml"
	code := fmt.Sprintf(`[package]
name = "%s"
version = "0.1.0"
edition = "2024"

[dependencies]
`, gen.options.Rust.CrateName)
	if err := outdir.AddCodeFile(filepathName, code); err != nil {
		return err
	}
	filepathName = ".gitignore"
	code = `/target
`
	if err := outdir.AddCodeFile(filepathName, code); err != nil {
		return err
	}
	filepathName = "src/lib.rs"
	code = `pub fn add(left: u64, right: u64) -> u64 {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
`
	if err := outdir.AddCodeFile(filepathName, code); err != nil {
		return err
	}

	return outdir.Write(gen.options, "Cargo.toml")
}

func (gen *genRust) InternalPrefix() string {
	if gen.options.Go.SplitInternal {
		return "internal."
	}
	return ""
}

func (gen *genRust) getNamespace(n string) *Namespace {
	na, ok := gen.Namespaces[n]
	if !ok {
		na = &Namespace{name: n}
		gen.Namespaces[n] = na
		// TODO - ALL golang-specific names
		na.decGo.DeconflictName("Handler")
		na.decGo.DeconflictName("Handle")
		na.decGo.DeconflictName("Client")
	}
	return na
}

func (gen *genRust) getType(t pure.TypeInstance) (*TypeRWWrapper, error) {
	result, ok := gen.generatedTypes[t.CanonicalName()]
	if !ok {
		return nil, fmt.Errorf("internal error: type %q not found", t.CanonicalName())
	}
	return result, nil
}

func (gen *genRust) getTypeMust(t pure.TypeInstance) *TypeRWWrapper {
	result, ok := gen.generatedTypes[t.CanonicalName()]
	if !ok {
		panic(fmt.Errorf("internal error: type instance %q not found", t.CanonicalName()))
	}
	return result
}

func (gen *genRust) getTypeWrapperMust(rt tlast.TL2TypeRef) (*TypeRWWrapper, bool) {
	ref, fieldBare, err := gen.kernel.GetInstance(rt)
	if err != nil {
		panic(fmt.Errorf("internal error: cannot get type of argument %s: %w", rt.String(), err))
	}
	return gen.getTypeMust(ref), fieldBare
}
